# -*- coding: utf-8 -*-
"""Gera estrutura.json e index.html. Executar: python _build_html.py"""
import csv
import json
from pathlib import Path

DIR = Path(__file__).parent
CSV_PATH = DIR.parent / "Estrutura_Evolucao_Projeto.csv"
ESTRUTURA_OUT = DIR / "estrutura.json"
INDEX_OUT = DIR / "index.html"

CSV_PCT = {}
with open(CSV_PATH, encoding="utf-8-sig") as f:
    for row in csv.DictReader(f, delimiter=";"):
        pid = row["ID"].strip()
        pct = row["Percentual"].strip()
        if pct:
            CSV_PCT[pid] = int(pct)


FORA_PLANO_ORIGINAL = {
    # Levantamento — trabalho de projeto, não funcionalidade do RFP
    "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7",
    "cms-arc-1",
    # Evoluções além do escopo_original_cliente.txt
    "2.2.10",
    "2.4.2.3", "2.4.2.4", "2.4.2.9", "2.4.3.11",
    "be-entrevista-modelo",
    "ges-entrevista-convocar",
    "2.4.4.2", "2.4.4.3", "2.4.4.4",
    "2.4.4.2-ph", "2.4.4.3-ph", "2.4.4.2-on", "2.4.4.3-on",
    "ges-doacao-on-live", "ges-doacao-on-funil", "ges-doacao-massa", "ges-pos-pix", "ges-pos-recibo",
    "cli-doacao-on-100", "cli-doacao-on-live", "cli-doacao-on-kw", "cli-doacao-on-quiz",
    "cli-status-ux", "cli-pos-pix", "cli-pos-recibo", "be-doacao-on-funil", "be-pos-doacao",
    # Doação — extensões 27/ago (itens 1:N, orçamento por unidade)
    "ges-doacao-itens", "be-doacao-itens",
    "cms-orcamento-unidade", "ges-orcamento-unidade", "be-orcamento-unidade",
    "ges-doacao-on-timestamp-quiz",
    "2.4.2.7",
    "cms-alertas", "cms-pacotes-comunicacao", "ges-alertas-binding", "be-fila-alertas", "be-alertas-eval", "alertas-resumo",
    # legado id — agora coberto por alertas Backend (não Mautic)
    "2.3.5.7",
    "2.6.6",
    "imp-1", "imp-2", "imp-3", "imp-4", "imp-5", "imp-6",
    "2.8.1", "2.8.3",
    # Extensões da capacidade Classificar inscritas (régua 6 critérios)
    "2.2.7-regua",
    "2.4.2.1-ext-score",
    "2.5.1.4b-regua",
    "2.3.2.3-score",
    # Extensões da capacidade Cadastro / inscrição (formulário dinâmico)
    "cms-cadastro-form-dinamico",
    "2.5.1.4-ext-schema",
    "be-cadastro-schema",
    "ges-cadastro-ficha-dinamica",
    # Extensões Registro de faturamento (4→7 indicadores + dificuldade)
    "cms-tipo-faturamento-7",
    "cms-tipo-faturamento-dificuldade",
    "ges-tipo-faturamento-7",
    "ges-tipo-faturamento-dificuldade",
    "cli-tipo-faturamento-7",
    "cli-tipo-faturamento-dificuldade",
    "be-tipo-faturamento-7",
    "be-tipo-faturamento-dificuldade",
    "cms-tipo-faturamento-anexo",
    "ges-tipo-faturamento-anexo",
    "cli-tipo-faturamento-anexo",
    "be-tipo-faturamento-anexo",
    "bi-tipo-faturamento-7",
    "bi-tipo-faturamento-dificuldade",
    # BI — além do escopo (Painel Looker / UC59+)
    "bi-metas-institucionais",
    "bi-capital-semente-doacoes",
    "bi-mapa-regioes",
    "bi-mentorias",
    "bi-tipos-doacao-valores",
    "bi-pessoas-empreendimentos",
    "bi-analise-persona",
    "ges-conteudo-extra",
    "cli-aula-replay",
    "2.4.3.8-qr",
    "2.4.3.13",
}

CAP_CLASSIFICAR = "classificar-inscritas"
CAP_CLASSIFICAR_LABEL = "Classificar inscritas"
CAP_ENTREVISTA = "entrevista-selecao"
CAP_ENTREVISTA_LABEL = "Entrevista de seleção (P/H)"
CAP_CADASTRO = "cadastro-inscricao"
CAP_CADASTRO_LABEL = "Cadastro / inscrição da empreendedora"
CAP_DOACAO_PH = "doacao-ph"
CAP_DOACAO_PH_LABEL = "Doação P/H"
CAP_DOACAO_ON = "doacao-online"
CAP_DOACAO_ON_LABEL = "Doação online"
CAP_POS_DOACAO = "pos-liberacao-doacao"
CAP_POS_DOACAO_LABEL = "Pós-liberação da doação"
CAP_ALERTAS = "alertas-engajamento"
CAP_ALERTAS_LABEL = "Alertas de engajamento"
CAP_COMUNICACAO = "comunicacao-uc88"
CAP_COMUNICACAO_LABEL = "Comunicação unificada (UC88)"


def item_tipo(id_, title, what, when, spec, csv_id=None, parte=None, impacta_modelo=False):
    parte = parte or spec["parte"]
    plano = bool(spec["plano"]) if parte == "nucleo" else False
    return item(
        id_,
        title,
        what,
        when,
        spec["scope"],
        csv_id or spec["csv"],
        plano_original=plano,
        capacidade=spec["slug"],
        capacidade_label=spec["label"],
        capacidade_parte=parte,
        impacta_modelo=impacta_modelo,
    )


# Tipos educacionais (UC15 / Tipos_de_Atividade.md). 11 tipos canônicos.
# Operação no Desenvolvimento (CMS/Gestor/Cliente/Backend/msg); visão C-level no catálogo 1.2.
TIPOS_ATIVIDADE = [
    {
        "slug": "tipo-aula",
        "label": "Aula",
        "scope": "MVP",
        "csv": "2.5.3.1",
        "plano": True,
        "parte": "nucleo",
        "when": "Encontros P/H (presencial ou ao vivo)",
        "cms": "Cadastrar a aula no módulo: **natureza original** (presencial/ao vivo), título e descrição (UC15). Unifica presencial e ao vivo. **Sem** data/hora/local/link no CMS. Não existe em edição 100% online.",
        "gestor": "Liberar com natureza **default** do CMS (editável até ministrar); presencial: data, hora, endereço; QR e chamada; relato. Ao vivo: data, hora, link Meet/plataforma; comparecimento. Comunicar no grupo da turma.",
        "cliente": "Presencial: ver local/material e confirmar presença (QR). Ao vivo: entrar na transmissão no horário.",
        "msg": "Mensagem no grupo com data, horário e endereço ou link; lembrete antes da sessão.",
        "backend": "Presença/comparecimento conta no progresso e no beneficiamento; após qualquer presença a liberação não pode ser cancelada. Inexistente em edição online.",
        "extensoes": [
            "QR Code e chamada manual (natureza presencial)",
            "Relato do encontro (natureza presencial)",
            "Replay opcional (natureza ao vivo — sem nova presença)",
        ],
    },
    {
        "slug": "tipo-video-aula",
        "label": "Vídeo Aula",
        "scope": "MVP",
        "csv": "2.5.3.2",
        "plano": True,
        "parte": "nucleo",
        "when": "Durante módulos",
        "cms": "Publicar o vídeo no módulo (título, descrição, arquivo na plataforma educacional). Em online, pode haver também arquivo compatível com WhatsApp (UC51); conclusão oficial permanece na plataforma.",
        "gestor": "Liberar com data-prazo (sugestão D+2); ver quem assistiu; comunicar o link.",
        "cliente": "Assistir o conteúdo gravado no aplicativo, no próprio ritmo, até o percentual de conclusão.",
        "msg": "Mensagem com prazo e link da aula; lembrete de vencimento para quem ainda não assistiu.",
        "backend": "Conclusão com percentual assistido (padrão 80%, configurável); conta no beneficiamento.",
    },
    {
        "slug": "tipo-atividade",
        "label": "Atividade (questionário genérico)",
        "scope": "Fase 2",
        "csv": "2.5.3.8",
        "plano": True,
        "parte": "nucleo",
        "when": "Conforme módulo",
        "cms": "Montar o questionário genérico no módulo (perguntas objetivas e abertas), distinto do inicial, do final e do NPS.",
        "gestor": "Liberar com data-prazo; ver quem respondeu; consultar consolidado e respostas abertas. Sem fila de aprovação.",
        "cliente": "Responder o questionário no aplicativo até o prazo.",
        "msg": "Mensagem com prazo e link; lembrete de vencimento.",
        "backend": "Marcar realizado / não realizado; respostas alimentam consolidado da turma.",
    },
    {
        "slug": "tipo-tarefa-casa",
        "label": "Tarefa de casa",
        "scope": "MVP",
        "csv": "2.5.3.5",
        "plano": True,
        "parte": "nucleo",
        "when": "Conforme módulo",
        "cms": "Cadastrar a tarefa no módulo: enunciado, dica e arquivos de referência (pré-carregados do CMS; gestor só define prazo).",
        "gestor": "Liberar com data-prazo; conferir entregas; aprovar ou pedir revisão (sem reprovação); comentar com a empreendedora; comunicar o prazo.",
        "cliente": "Baixar o material de apoio, realizar o exercício e enviar arquivo ou resposta no aplicativo.",
        "msg": "Mensagem com prazo e link para enviar; lembrete de vencimento; aviso quando a gestora pedir revisão.",
        "backend": "Fila aprovar / revisar (sem reprovação); entrega conta no beneficiamento após aprovação.",
    },
    {
        "slug": "tipo-faturamento",
        "label": "Registro de faturamento",
        "scope": "MVP",
        "csv": "2.5.3.7",
        "plano": True,
        "parte": "nucleo",
        "when": "Competência mensal",
        "cms": "Incluir o registro periódico no módulo (mês de referência). Núcleo do plano original: **4 indicadores** — renda, faturamento, investimento e poupança. Reporte ao programa, não fluxo de caixa pessoal.",
        "gestor": "Liberar com data-prazo; conferir e aprovar ou pedir revisão os **4 indicadores** do núcleo; acompanhar a evolução da turma. Zero em faturamento/renda exige justificativa.",
        "cliente": "Informar no aplicativo os **4 indicadores** do mês (renda, faturamento, investimento, poupança); justificar se faturamento ou renda = 0.",
        "msg": "Mensagem com prazo e link do formulário; lembrete de vencimento.",
        "backend": "Um registro por competência e empreendimento; só o aprovado conta; persiste os 4 indicadores do núcleo; zero sem observação bloqueia envio.",
        "extensoes": [
            "+3 indicadores: despesas fixas, nº de clientes, nº de produtos vendidos",
            "Autoavaliação de dificuldade (5 rostos)",
            "Anexo obrigatório (planilha, foto ou print)",
        ],
        "impacta_modelo": True,
    },
    {
        "slug": "tipo-download",
        "label": "Download de conteúdo",
        "scope": "MVP",
        "csv": "2.5.3.6",
        "plano": True,
        "parte": "nucleo",
        "when": "Conforme módulo",
        "cms": "Anexar o material de apoio no módulo (caderno, planilha, checklist, kit de artes).",
        "gestor": "Liberar com data-prazo; ver quem baixou. Online: template + arquivos no WhatsApp após OK; P/H: comunicar o template no grupo. Arquivos também no Cliente.",
        "cliente": "Baixar o arquivo no aplicativo (os mesmos docs também chegam no WhatsApp na online). Sem envio de volta.",
        "msg": "Template Download + arquivos no WhatsApp da usuária (online, após OK); os mesmos documentos no Cliente. Lembrete se ainda não baixou.",
        "backend": "Enviar arquivos no lote pós-OK (independente da flag de videoaula). Marcar baixou / não baixou no Cliente; conta no beneficiamento após o download na plataforma.",
    },
    {
        "slug": "tipo-plano-acao",
        "label": "Plano de ação",
        "scope": "Fase 2",
        "csv": "2.5.3.10",
        "plano": False,
        "parte": "nucleo",
        "when": "Conforme módulo",
        "cms": "Incluir o plano de ação no módulo (orientação para metas do empreendimento). Não estava no plano original como tipo próprio.",
        "gestor": "Liberar com data-prazo; ver quem fez; criar, Revisar (com observação) e acompanhar metas; histórico preservado (sem exclusão destrutiva); comunicar o prazo.",
        "cliente": "Preencher o plano e acompanhar as metas no aplicativo; responder quando a gestora pedir revisão.",
        "msg": "Mensagem com prazo e link do plano; lembrete de vencimento; aviso de revisão.",
        "backend": "Marcar fez / não fez; histórico de edições das metas; status pode ir para análise das gestoras.",
    },
    {
        "slug": "tipo-visita-tecnica",
        "label": "Visita técnica",
        "scope": "Fase 2",
        "csv": "2.5.3.11",
        "plano": False,
        "parte": "nucleo",
        "when": "Agendamento P/H",
        "cms": "Disponibilizar o tipo visita no módulo (só presencial/híbrido). Não estava no plano original.",
        "gestor": "Abrir agenda de visitas: data, hora e local ou videoconferência por empreendedora; agrupamento de endereços próximos (~2 km) e detecção de conflito; registrar o observado; comunicar o agendamento.",
        "cliente": "Ver data e local (ou link) da visita no aplicativo; receber o registro depois da visita.",
        "msg": "Mensagem de agendamento e lembrete; não há grupo coletivo para este tipo.",
        "backend": "Não existe em edição 100% online; visita realizada conta no progresso da participante.",
    },
    {
        "slug": "tipo-q-inicial",
        "label": "Questionário inicial",
        "scope": "MVP",
        "csv": "2.5.3.3",
        "plano": True,
        "parte": "nucleo",
        "when": "Início da jornada",
        "cms": "Cadastrar o instrumento de diagnóstico de entrada (T0) no módulo, com as perguntas definidas pela equipe.",
        "gestor": "Liberar com data-prazo; ver quem respondeu; consultar o consolidado da turma (pizza / adesão).",
        "cliente": "Responder o diagnóstico no aplicativo, no início do curso.",
        "msg": "Mensagem com prazo e link; lembrete de vencimento.",
        "backend": "Respostas T0 ficam disponíveis para comparar com o questionário final e com os indicadores qualitativos.",
    },
    {
        "slug": "tipo-q-final",
        "label": "Questionário final",
        "scope": "MVP",
        "csv": "2.5.3.4",
        "plano": True,
        "parte": "nucleo",
        "when": "Fim da jornada",
        "cms": "Cadastrar o instrumento de avaliação de saída (T1) no módulo. Em online (funil UC38), só libera após KW válida da atividade de presença pós-live.",
        "gestor": "Liberar com data-prazo no encerramento; ver quem respondeu; comparar com o diagnóstico inicial. Encerramento P/H = módulo obrigatório de carga (≠ funil online).",
        "cliente": "Responder a avaliação de saída no aplicativo (online: após presença/KW da live).",
        "msg": "Mensagem com prazo e link; lembrete de vencimento.",
        "backend": "Insumo do encerramento e da consolidação de beneficiamento; compara T0 e T1; online: trava pós-KW e 100% certo para liberar doação.",
    },
    {
        "slug": "tipo-nps",
        "label": "NPS",
        "scope": "Fase 2",
        "csv": "2.5.3.12",
        "plano": True,
        "parte": "nucleo",
        "when": "Encerramento",
        "cms": "Incluir a pesquisa de satisfação (NPS) no módulo, com máscara única para online, presencial e híbrido.",
        "gestor": "Liberar com data-prazo; ver respondentes e faixas (promotoras, neutras, detratoras).",
        "cliente": "Responder a pesquisa de satisfação no aplicativo.",
        "msg": "Mensagem com prazo e link; lembrete de vencimento.",
        "backend": "Classificar respostas em promotora / neutra / detratora; alimentar relatório de avaliação do curso.",
    },
]


def tipo_by_slug(slug):
    return next(t for t in TIPOS_ATIVIDADE if t["slug"] == slug)


def slices_tipo(spec):
    """Fatias operacionais no Desenvolvimento (CMS/Gestor/Cliente/Backend/mensageria)."""
    slug = spec["slug"]
    label = spec["label"]
    when = spec["when"]
    return {
        "cms": item_tipo(
            f"cms-{slug}",
            f"{label} — cadastrar no módulo",
            spec["cms"],
            "Antes da aplicação",
            spec,
            "2.2.6",
        ),
        "gestor": item_tipo(
            f"ges-{slug}",
            f"{label} — interface de gestão",
            spec["gestor"],
            when,
            spec,
            "2.4.3.6",
        ),
        "cliente": item_tipo(
            f"cli-{slug}",
            f"{label} — exibir e operacionalizar no Cliente",
            spec["cliente"],
            when,
            spec,
            spec["csv"],
        ),
        "backend": item_tipo(
            f"be-{slug}",
            f"{label} — API, regras e persistência",
            spec["backend"],
            when,
            spec,
            "2.3.3.0",
        ),
        "msg": item_tipo(
            f"msg-{slug}",
            f"{label} — mensagens e lembretes",
            spec["msg"],
            when,
            spec,
            "2.6.5",
        ),
    }


def item_catalogo_tipo(spec):
    """Folha C-level do catálogo 1.2: um tipo, com % núcleo + % extensão."""
    extras = spec.get("extensoes") or []
    what = spec["cms"]
    if extras:
        what = what + " Extensões: " + "; ".join(extras) + "."
    return item(
        f"cat-{spec['slug']}",
        spec["label"],
        what,
        spec["when"],
        spec["scope"],
        spec["csv"],
        plano_original=bool(spec["plano"]),
        capacidade=spec["slug"],
        capacidade_label=spec["label"],
        capacidade_parte=spec["parte"],
        extensoes=extras,
        catalogo_tipo=True,
        impacta_modelo=bool(spec.get("impacta_modelo")),
    )


def item(
    id_,
    title,
    what,
    when,
    scope="MVP",
    csv_id=None,
    default=None,
    plano_original=None,
    capacidade=None,
    capacidade_label=None,
    capacidade_parte=None,
    impacta_modelo=False,
    extensoes=None,
    catalogo_tipo=False,
):
    pct = default
    if csv_id and csv_id in CSV_PCT:
        pct = CSV_PCT[csv_id]
    if plano_original is None:
        plano_original = id_ not in FORA_PLANO_ORIGINAL
    data = {
        "id": id_,
        "csvId": csv_id or id_,
        "title": title,
        "what": what,
        "when": when,
        "scope": scope,
        "defaultPct": pct,
        "planoOriginal": plano_original,
    }
    if capacidade:
        data["capacidade"] = capacidade
        data["capacidadeLabel"] = capacidade_label or capacidade
        data["capacidadeParte"] = capacidade_parte or "nucleo"
    if impacta_modelo:
        data["impactaModelo"] = True
    if extensoes:
        data["extensoes"] = list(extensoes)
    if catalogo_tipo:
        data["catalogoTipo"] = True
        data["defaultPctExtensao"] = 0
    return data


TIPO_SLICES = [slices_tipo(t) for t in TIPOS_ATIVIDADE]
CMS_TIPOS = [s["cms"] for s in TIPO_SLICES]
GES_TIPOS = [s["gestor"] for s in TIPO_SLICES]
CLI_TIPOS = [s["cliente"] for s in TIPO_SLICES]
MSG_TIPOS = [s["msg"] for s in TIPO_SLICES]
BE_TIPOS = [s["backend"] for s in TIPO_SLICES]
CAT_TIPOS = [item_catalogo_tipo(t) for t in TIPOS_ATIVIDADE]

_FAT = tipo_by_slug("tipo-faturamento")
_FAT_LABEL = _FAT["label"]
_FAT_WHEN = _FAT["when"]
_AULA = tipo_by_slug("tipo-aula")

CMS_TIPOS.extend(
    [
        item(
            "cms-tipo-faturamento-7",
            "Registro de faturamento — 7 indicadores",
            "Extensão: além dos 4 do plano (renda, faturamento, investimento, poupança), o módulo passa a coletar despesas fixas, nº de clientes e nº de produtos vendidos.",
            "Antes da aplicação",
            "MVP",
            "2.2.6",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "cms-tipo-faturamento-dificuldade",
            "Registro de faturamento — indicador de dificuldade",
            "Extensão: configurar a coleta obrigatória da autoavaliação de dificuldade (5 níveis com rostos) no registro mensal.",
            "Antes da aplicação",
            "MVP",
            "2.2.6",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "cms-tipo-faturamento-anexo",
            "Registro de faturamento — anexo obrigatório",
            "Extensão: exigir anexo (planilha, foto ou print) no envio do registro mensal.",
            "Antes da aplicação",
            "MVP",
            "2.2.6",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
    ]
)

GES_TIPOS.extend(
    [
        item_tipo(
            "2.4.3.8-qr",
            "Aula — QR Code e chamada (presencial)",
            "Extensão operacional da natureza presencial: QR imprimível e registro manual por nome ou CPF.",
            "Cada aula presencial",
            _AULA,
            "2.4.3.8",
            parte="extensao",
        ),
        item_tipo(
            "2.4.3.13",
            "Aula — relato do encontro (presencial)",
            "Extensão operacional: campo 'Como foi o encontro' e exportação da presença após a realização.",
            "Após a aula presencial",
            _AULA,
            "2.4.3.13",
            parte="extensao",
        ),
        item(
            "ges-conteudo-extra",
            "Conteúdo extra (UC35)",
            "Fora da enum TipoAtividade: gestor de turma adiciona item pontual além da matriz (presencial ou ao vivo). Não conta %/carga/beneficiamento; enquanto não liberado, pode ser excluído.",
            "Durante a aplicação P/H",
            "MVP",
            "2.4.3.12",
            plano_original=False,
        ),
        item(
            "ges-tipo-faturamento-7",
            "Registro de faturamento — conferir 7 indicadores",
            "Extensão: na aprovação, conferir também despesas fixas, clientes e produtos vendidos (além dos 4 do núcleo).",
            _FAT_WHEN,
            "MVP",
            "2.4.3.9",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "ges-tipo-faturamento-dificuldade",
            "Registro de faturamento — ver dificuldade na aprovação",
            "Extensão: exibir a dificuldade declarada no modal de aprovação, no histórico por competência e no resumo da turma (distribuição dos 5 níveis).",
            _FAT_WHEN,
            "MVP",
            "2.4.3.9",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "ges-tipo-faturamento-anexo",
            "Registro de faturamento — conferir anexo",
            "Extensão: na aprovação, verificar o anexo obrigatório do registro mensal.",
            _FAT_WHEN,
            "MVP",
            "2.4.3.9",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
        ),
    ]
)

CLI_TIPOS.extend(
    [
        item(
            "cli-tipo-faturamento-7",
            "Registro de faturamento — preencher 7 indicadores",
            "Extensão: além de renda, faturamento, investimento e poupança, informar despesas fixas, nº de clientes e nº de produtos vendidos.",
            _FAT_WHEN,
            "MVP",
            "2.5.3.7",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "cli-tipo-faturamento-dificuldade",
            "Registro de faturamento — declarar dificuldade",
            "Extensão: escolher obrigatoriamente a dificuldade do preenchimento (5 rostos: muito difícil → muito fácil).",
            _FAT_WHEN,
            "MVP",
            "2.5.3.7",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "cli-tipo-faturamento-anexo",
            "Registro de faturamento — enviar anexo",
            "Extensão: anexar planilha, foto ou print; sem anexo o envio é bloqueado.",
            _FAT_WHEN,
            "MVP",
            "2.5.3.7",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item_tipo(
            "cli-aula-replay",
            "Aula — replay (ao vivo)",
            "Extensão: assistir a gravação depois da transmissão, sem gerar nova presença.",
            "Após a aula ao vivo",
            _AULA,
            "2.5.3.1",
            parte="extensao",
        ),
    ]
)

BE_TIPOS.extend(
    [
        item(
            "be-tipo-faturamento-7",
            "Registro de faturamento — persistir 7 indicadores",
            "Extensão: modelo e validação dos 3 campos adicionais (despesas fixas, clientes, produtos); séries históricas passam a carregar o conjunto ampliado.",
            _FAT_WHEN,
            "MVP",
            "2.5.3.7",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "be-tipo-faturamento-dificuldade",
            "Registro de faturamento — persistir dificuldade",
            "Extensão: gravar a escala de 5 níveis; bloquear envio sem dificuldade; disponibilizar agregados para o Gestor e o BI.",
            _FAT_WHEN,
            "MVP",
            "2.5.3.7",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
        item(
            "be-tipo-faturamento-anexo",
            "Registro de faturamento — persistir anexo",
            "Extensão: armazenar o anexo obrigatório; rejeitar submit sem arquivo.",
            _FAT_WHEN,
            "MVP",
            "2.5.3.7",
            capacidade="tipo-faturamento",
            capacidade_label=_FAT_LABEL,
            capacidade_parte="extensao",
            impacta_modelo=True,
        ),
    ]
)


ESTRUTURA = {
    "version": "1.6",
    "meta": {
        "title": "Consulado da Mulher — Acompanhamento do Projeto",
        "scopes": ["MVP", "Fase 2", "Fase 3"],
        "andamentoStatuses": ["Não iniciado", "Em andamento"],
        "planoOriginalLabel": "Plano original do cliente",
        "planoOriginalRef": "../escopo_original_cliente.txt",
        "capacidadePartes": ["nucleo", "extensao"],
        "updated": "2026-08-30",
        "specRef": "../Casos de Uso - Consulado da Mulher_v7.md",
        "comercialRef": "../fora_escopo_v2.md",
    },
    "csvDefaults": CSV_PCT,
    "phases": [
        {
            "id": "phase-levantamento",
            "title": "Levantamento",
            "desc": "Definição do produto, regras de negócio e validação com stakeholders antes da construção.",
            "artifacts": [
                {
                    "id": "art-doc",
                    "title": "Documentação e validação",
                    "desc": "Base acordada que orienta todo o sistema.",
                    "blocks": [
                        {
                            "title": "Entregas de levantamento",
                            "items": [
                                item("1.1", "Casos de uso e regras de negócio", "Documento **v7** (85 UCs): inscrição, seleção 3 etapas (UC84 P/H), jornada, comunicação UC88/UC87, doação por modalidade. Abaixo: extras fora do plano original (to-do de documentação).", "Antes do desenvolvimento", "MVP", "1.1", 70),
                                item("1.3", "Modelo conceitual de dados", "Como se relacionam programa, edição, unidade, turma, empreendedora e empreendimento. Abaixo: extras que crescem o modelo.", "Antes da construção", "MVP", "1.3"),
                                item("1.4", "Validação do protótipo — App Gestor", "Telas validadas para operação da equipe (seleção, turma, acompanhamento).", "Com gestores de unidade e turma", "MVP", "1.4", 80),
                                item("1.5", "Validação do protótipo — Painel Admin", "Telas validadas para montagem de programas e edições.", "Com administradores de programa", "MVP", "1.5", 80),
                                item("1.6", "Validação do protótipo — App Cliente", "Fluxo de inscrição e jornada da empreendedora validado.", "Com equipe de programa", "MVP", "1.6"),
                                item("1.7", "Identidade visual e experiência mobile", "Padrão visual e uso prioritário no celular.", "Antes do desenvolvimento das telas", "MVP", "1.7"),
                            ],
                        },
                        {
                            "title": "1.2 Catálogo de tipos de atividade",
                            "items": CAT_TIPOS,
                        },
                    ],
                }
            ],
        },
        {
            "id": "phase-desenvolvimento",
            "title": "Desenvolvimento",
            "desc": "Construção dos painéis, aplicativos, motor de regras e integrações que sustentam cada edição.",
            "artifacts": [
                {
                    "id": "art-cms",
                    "title": "CMS Administrativo",
                    "desc": "Montar o programa antes de abrir inscrições — estrutura-mãe que alimenta Gestor e Cliente.",
                    "blocks": [
                        {
                            "title": "Arcabouço do sistema",
                            "items": [
                                item("cms-arc-1", "Estrutura-mãe por edição", "Tudo que a equipe e a empreendedora veem em cada edição nasce da configuração feita aqui.", "Antes de cada ciclo", "MVP"),
                                item("cms-arc-2", "Perfis de acesso da equipe", "Quem administra o programa, quem opera a unidade e quem opera a turma.", "Cadastro inicial da equipe", "MVP", "2.2.2"),
                            ],
                        },
                        {
                            "title": "Cadastros necessários",
                            "items": [
                                item("2.2.1", "Acesso administrativo", "Login seguro da equipe de configuração.", "Uso contínuo", "MVP", "2.2.1"),
                                item("2.2.3", "Programas (metodologia)", "Modelo reutilizável de capacitação; modalidade online/P/H; duração Longa / Média / Curta para o BI.", "Antes de abrir edições", "MVP", "2.2.3"),
                                item("2.2.4", "Edições", "Calendário de inscrição, seleção e aplicação; modalidade; metas de beneficiados; orçamento de doação **por unidade**; prazo pós-live (online).", "Por edição", "MVP", "2.2.4"),
                                item(
                                    "cms-orcamento-unidade",
                                    "Orçamento de doação por unidade",
                                    "Extensão: Admin define teto R$ **por unidade** na edição (UC9) — **somente no CMS**; Gestor consulta saldos (UC57). Impacta modelo.",
                                    "Por edição",
                                    "MVP",
                                    "2.2.4",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                    impacta_modelo=True,
                                ),
                                item("2.2.5", "Unidades", "Pontos regionais de operação.", "Por edição", "MVP", "2.2.5"),
                                item("2.2.6", "Módulos e tipos de atividade", "Sequência pedagógica: o administrador monta cada módulo com os **11 tipos** canônicos (UC15). **Aula** unifica presencial e ao vivo (natureza na liberação). Progresso C-level = catálogo 1.2; aqui é a operação no CMS. Conteúdo extra (UC35) fica fora da enum.", "Antes da aplicação", "MVP", "2.2.6"),
                                item(
                                    "2.2.7-bloqueio",
                                    "Bloqueios de inscrição",
                                    "Quem não pode se cadastrar: idade menor de 18 e, no presencial/híbrido, indisponibilidade para encontros.",
                                    "Por edição",
                                    "MVP",
                                    "2.2.7",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "2.2.7-regua",
                                    "Régua pontuável — 6 critérios",
                                    "Ativar ou desativar até 6 critérios (tempo de negócio, renda, CLT, cargo público, internet, WhatsApp) e cortes por edição. Score X/Y apoia a classificação — não aprova automaticamente.",
                                    "Por edição",
                                    "MVP",
                                    "2.2.7",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="extensao",
                                ),
                                item(
                                    "cms-cadastro-ficha-base",
                                    "Ficha de inscrição — base da edição",
                                    "Configurar a ficha unificada da inscrição: texto de instruções, categorias de faturamento e Guia do Participante. Núcleo do cadastro no sistema (substitui Google Forms).",
                                    "Por edição",
                                    "MVP",
                                    "2.2.4",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "cms-cadastro-form-dinamico",
                                    "Formulário dinâmico da inscrição",
                                    "Extensão: Admin monta campos e perguntas variáveis por edição (ordem, tipo, obrigatoriedade, bloco, show/hide). Impacta CMS, Cliente, Backend, modelo de dados, Gestor e o que entra ou não no BI.",
                                    "Por edição",
                                    "MVP",
                                    "2.2.4",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="extensao",
                                    impacta_modelo=True,
                                ),
                                item("2.2.8", "Beneficiamento e certificação", "Percentual de conclusão para certificar e considerar beneficiada.", "Por edição", "MVP", "2.2.8"),
                                item("2.2.9", "Encerramento de edição", "Congelar a operação após o fim do ciclo.", "Fim da edição", "MVP", "2.2.9"),
                            ],
                        },
                        {
                            "title": "Comunicação unificada (UC88)",
                            "items": [
                                item(
                                    "cms-pacotes-comunicacao",
                                    "Pacotes de comunicação (UC88)",
                                    "Catálogo CMS reutilizável: templates Meta/Gupshup — **1 por** `TipoAtividade` (Aula: presencial + ao_vivo); momentos de jornada; mesmo corpo alimenta API online (UC33) e clipboard P/H (UC50). Edição **seleciona pacote** (UC9).",
                                    "Antes / durante edições",
                                    "MVP",
                                    "2.6.1",
                                    capacidade=CAP_COMUNICACAO,
                                    capacidade_label=CAP_COMUNICACAO_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "cms-alertas",
                                    "Alertas automáticos — aba Alertas (UC87)",
                                    "Na **mesma área Comunicação (UC88)**: regras tipadas (gatilho + params + canal + cadência + exitWhen). Execução no Backend (UC52) — sem Mautic.",
                                    "Antes / durante edições",
                                    "MVP",
                                    "2.3.5.7",
                                    capacidade=CAP_ALERTAS,
                                    capacidade_label=CAP_ALERTAS_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                            ],
                        },
                        {
                            "title": "Tipos de atividade nos módulos",
                            "items": CMS_TIPOS,
                        },
                    ],
                },
                {
                    "id": "art-gestor",
                    "title": "Aplicativo Gestor",
                    "desc": "Operar a edição do início ao encerramento — equipe de unidade e de turma no mesmo aplicativo.",
                    "blocks": [
                        {
                            "title": "A. Entrada",
                            "items": [
                                item("2.4.1.1", "Acesso por link seguro", "Gestor entra por e-mail, sem senha.", "Sempre", "MVP", "2.4.1.1"),
                                item("2.4.1.2", "Lista de edições", "Visão das edições sob responsabilidade do colaborador.", "Após login", "MVP", "2.4.1.2"),
                                item("2.4.1.4", "Painel operacional da edição", "Indicadores rápidos: inscritas, pendentes, próximos passos.", "Ao abrir uma edição", "MVP", "2.4.1.4"),
                            ],
                        },
                        {
                            "title": "B. Seleção de participantes",
                            "items": [
                                item(
                                    "2.4.2.1",
                                    "Classificar inscritas",
                                    "Listar inscritas e marcar qualificada, em análise ou não qualificada com base no cadastro. Não inicia o curso.",
                                    "Fase de seleção",
                                    "MVP",
                                    "2.4.2.1",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "2.4.2.1-ext-score",
                                    "Score X/Y na classificação",
                                    "Exibir pontuação da régua (X de Y critérios ativos) e o detalhe de cada critério no painel de classificação. Apoia a decisão; não substitui o status manual.",
                                    "Fase de seleção",
                                    "MVP",
                                    "2.4.2.1",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="extensao",
                                ),
                                item("2.4.2.3", "Agrupar empreendimentos", "Unir sócias do mesmo negócio informal em um único empreendimento.", "Durante a seleção", "MVP", "2.4.2.3"),
                                item(
                                    "2.4.2.4",
                                    "Entrevista de seleção",
                                    "Extensão da seleção P/H (não está no RFP): criar sessões, agendar qualificadas (convocação), registrar presença/ausência, aprovar ou realocar. Ausente → não aprovada automaticamente (salvo realocação). Só P/H — online segue classificar → comunicar.",
                                    "Seleção P/H",
                                    "MVP",
                                    "2.4.2.4",
                                    capacidade=CAP_ENTREVISTA,
                                    capacidade_label=CAP_ENTREVISTA_LABEL,
                                    capacidade_parte="extensao",
                                    impacta_modelo=True,
                                ),
                                item(
                                    "ges-entrevista-convocar",
                                    "Convocar para a entrevista (faixa de comunicação)",
                                    "Extensão: no Comunicar, enviar convite só a qualificadas **já alocadas em sessão** (UC25 faixa 1). Trava: sem alocação na entrevista não há convite.",
                                    "Seleção P/H",
                                    "MVP",
                                    "2.4.2.6",
                                    capacidade=CAP_ENTREVISTA,
                                    capacidade_label=CAP_ENTREVISTA_LABEL,
                                    capacidade_parte="extensao",
                                ),
                                item("2.4.2.5", "Alocar turmas", "Distribuir aprovadas pelas turmas da unidade (soft capacity — alerta sem hard lock).", "Após classificação/entrevista", "MVP", "2.4.2.5"),
                                item("2.4.2.6", "Comunicar resultado", "Informar aprovadas e não aprovadas. Este passo inicia a jornada educacional. Status Cliente humanizados.", "Fim da seleção", "MVP", "2.4.2.6"),
                                item("2.4.2.7", "Remanejar unidade/turma", "Mover participante entre unidades a qualquer momento (incl. pré-qualificação), com confirmação.", "Contínuo", "MVP", "2.4.2.5"),
                            ],
                        },
                        {
                            "title": "C. Antes e durante o curso",
                            "items": [
                                item("2.4.2.9", "Mini-CRM — resgatar inscrições", "Lista de quem começou e não terminou o cadastro; contato para concluir.", "Durante inscrição e seleção", "Fase 2", "2.4.2.9"),
                                item(
                                    "ges-cadastro-ficha-dinamica",
                                    "Ficha dinâmica na seleção e inserção assistida",
                                    "Extensão: ler respostas dos campos variáveis na classificação/ficha; quando autorizado (UC69), preencher o mesmo schema da edição no lugar da empreendedora.",
                                    "Seleção e operação",
                                    "MVP",
                                    "2.4.2.1",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="extensao",
                                    impacta_modelo=True,
                                ),
                                item("2.4.3.1", "Configurar turma e grupo WhatsApp", "Turma operacional + link do grupo para comunicação com a turma.", "Após aprovação", "MVP", "2.4.3.1"),
                                item("2.4.3.6", "Liberar atividades (presencial/híbrido)", "Gestor escolhe o que liberar módulo a módulo.", "Durante a aplicação P/H", "MVP", "2.4.3.6"),
                                item("2.4.3.7", "Acompanhar progresso (online)", "Visão do que foi liberado, enviado e concluído — jornada automática.", "Durante a aplicação online", "MVP", "2.4.3.7"),
                                item("2.4.3.8", "Registrar presença nos encontros", "Chamada por QR Code ou lista manual.", "Cada encontro presencial", "MVP", "2.4.3.8"),
                                item("2.4.3.9", "Aprovar tarefas e faturamento", "Validar entregas ou pedir revisão.", "Conforme prazos das atividades", "MVP", "2.4.3.9"),
                                item("2.4.3.10", "Comunicação no grupo WhatsApp", "Ferramenta para copiar mensagens e abrir o grupo da turma.", "Durante o curso P/H", "MVP", "2.4.3.10"),
                                item("2.4.3.11", "Painel de acompanhamento da turma", "Quem está engajada, quem parou; alertas de risco na jornada online.", "Contínuo", "Fase 2", "2.4.3.11"),
                                item(
                                    "ges-alertas-binding",
                                    "Alertas automáticos da edição",
                                    "Ativar/pausar regras do CMS, ajustar parâmetros, preview de audiência e histórico (UC87). Disparo manual UC53/UC26 como reforço.",
                                    "Durante a edição",
                                    "MVP",
                                    "2.4.3.11",
                                    capacidade=CAP_ALERTAS,
                                    capacidade_label=CAP_ALERTAS_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                            ],
                        },
                        {
                            "title": "Tipos de atividade — operação",
                            "items": GES_TIPOS,
                        },
                        {
                            "title": "D. Encerramento e doação",
                            "items": [
                                item("2.4.4.1", "Encerrar edição", "Fechar operação da edição (freeze).", "Após fim do calendário", "MVP", "2.4.4.1"),
                                item("2.4.4.1b", "Beneficiamento e certificados", "Emissão conforme percentual configurado na edição.", "Encerramento", "MVP", "2.3.4.1"),
                                item(
                                    "2.4.4.2-ph",
                                    "Doação P/H — sugerir a qualquer momento",
                                    "Análise manual: turma sugere doação em qualquer fase (modalidade + itens/valores); não depende de live nem questionário.",
                                    "Durante o programa P/H",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "2.4.4.3-ph",
                                    "Doação P/H — aprovar",
                                    "Unidade aprova ou recusa a sugestão (consome orçamento da unidade). Dois passos rastreáveis mesmo se a mesma pessoa sugeriu.",
                                    "Durante o programa P/H",
                                    "MVP",
                                    "2.4.4.3",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-doacao-on-live",
                                    "Doação online — live de encerramento",
                                    "Configurar live YouTube+StreamYard (fora da plataforma) e convidar só quem concluiu 100% das atividades.",
                                    "Fim da formação online",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-doacao-on-funil",
                                    "Doação online — acompanhar funil",
                                    "Ver quem fez 100%, entrou na live, validou presença/KW (prazo+timestamp) e acertou 100% no quiz (liberada para doação). Exibe data/hora exatas da conclusão do quiz.",
                                    "Fim da formação online",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-doacao-on-timestamp-quiz",
                                    "Doação online — timestamp do quiz",
                                    "Extensão: relatório/acompanhamento com data e horário exatos da conclusão do questionário final (além do timestamp da KW).",
                                    "Fim da formação online",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                ),
                                item(
                                    "2.4.4.2-on",
                                    "Doação online — sugerir (só liberadas)",
                                    "Sugerir doação (capital semente/material) apenas para quem passou no funil; suporte a doação em massa e múltiplos itens.",
                                    "Após liberação pelo funil",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "2.4.4.3-on",
                                    "Doação online — aprovar",
                                    "Unidade aprova ou recusa entre as liberadas pelo funil (individual ou massa). Consome orçamento da unidade. Ranking pós-elegibilidade ≠ régua inscrição.",
                                    "Após liberação pelo funil",
                                    "MVP",
                                    "2.4.4.3",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-doacao-massa",
                                    "Doação em massa",
                                    "Selecionar múltiplas participantes e aplicar modalidade/valor em lote (P/H ou liberadas online).",
                                    "Operação de doação",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-doacao-itens",
                                    "Doação — múltiplos itens (1:N)",
                                    "Extensão: cada doação admite N linhas (produto + valor) empilhadas. Gestor cadastra itens na sugestão/aprovação; material espelha no recibo. Impacta modelo.",
                                    "Operação de doação",
                                    "MVP",
                                    "2.4.4.2",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                    impacta_modelo=True,
                                ),
                                item(
                                    "ges-orcamento-unidade",
                                    "Orçamento de doação por unidade",
                                    "Extensão: saldos **disponível / consumido / em análise / saldo** por unidade na tela Doação (UC57). Valores definidos no CMS (UC9); Gestor **consulta**, não altera orçamento.",
                                    "Configuração e operação",
                                    "MVP",
                                    "2.4.4.3",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                    impacta_modelo=True,
                                ),
                                item(
                                    "2.4.4.4",
                                    "Lote auxiliar (carência / volume)",
                                    "Filtros auxiliares A–D e seleção em lote — não substituem análise P/H nem o funil online.",
                                    "Operação avançada",
                                    "Fase 2",
                                    "2.4.4.4",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-pos-pix",
                                    "Pós-liberação — solicitar PIX/conta",
                                    "Pedir conta ou PIX (CPF-PIX imutável se chave = CPF) e, se material, endereço com ponto de referência (comum P/H e online).",
                                    "Após liberada para doação",
                                    "MVP",
                                    "2.4.4.3",
                                    capacidade=CAP_POS_DOACAO,
                                    capacidade_label=CAP_POS_DOACAO_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "ges-pos-recibo",
                                    "Pós-liberação — gerar e acompanhar recibo",
                                    "Recibo conta 725 com prazo até 60 dias no texto; dinheiro assina antes, material após confirmação de recebimento; assinatura obrigatória; itens da doação no recibo; aceites.",
                                    "Após liberada para doação",
                                    "MVP",
                                    "2.4.4.3",
                                    capacidade=CAP_POS_DOACAO,
                                    capacidade_label=CAP_POS_DOACAO_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                            ],
                        },
                    ],
                },
                {
                    "id": "art-cliente",
                    "title": "Aplicativo Cliente",
                    "desc": "Jornada da empreendedora — do primeiro contato ao certificado.",
                    "blocks": [
                        {
                            "title": "A. Inscrição — três momentos",
                            "items": [
                                item("2.5.1.2", "1. Mini-CRM — aceites e captura inicial", "Link da edição, termos LGPD/WhatsApp, nome, telefone e e-mail. Equipe pode resgatar quem abandonou.", "Início da inscrição", "MVP", "2.5.1.2"),
                                item("2.5.1.3", "1. Mini-CRM — pré-cadastro", "Registro como lead antes da ficha completa.", "Início da inscrição", "MVP", "2.5.1.3"),
                                item(
                                    "2.5.1.4",
                                    "2. Cadastro completo",
                                    "Núcleo: ficha unificada em 4 blocos (instruções, pessoais, empreendimento, socioeconômico) + aceites + vínculo programa/edição/unidade. Substitui o Google Forms do RFP.",
                                    "Após pré-cadastro",
                                    "MVP",
                                    "2.5.1.4",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "2.5.1.4-ext-schema",
                                    "2. Cadastro — formulário dinâmico (schema da edição)",
                                    "Extensão: UI dirigida pelo schema da edição (progresso, show/hide, validação, retomada). Campos variáveis e Guia do Participante aparecem só quando configurados no CMS.",
                                    "Após pré-cadastro",
                                    "MVP",
                                    "2.5.1.4",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="extensao",
                                    impacta_modelo=True,
                                ),
                                item(
                                    "2.5.1.4b-bloqueio",
                                    "3. Cadastro da edição — bloqueios",
                                    "Perguntas da edição que impedem concluir a inscrição: idade e, no presencial/híbrido, disponibilidade para encontros; escolha de unidade.",
                                    "Mesma ficha, variável por edição",
                                    "MVP",
                                    "2.5.1.4",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "2.5.1.4b-regua",
                                    "3. Cadastro da edição — critérios pontuáveis",
                                    "Captura no cadastro dos dados usados pelos 6 critérios da régua (tempo de negócio, renda, CLT, cargo, internet, WhatsApp).",
                                    "Mesma ficha, variável por edição",
                                    "MVP",
                                    "2.5.1.4",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="extensao",
                                ),
                                item("2.5.1.5", "Confirmação e orientação WhatsApp", "Status em seleção + prazo estimado + contato com a organização.", "Fim da inscrição", "MVP", "2.5.1.5"),
                            ],
                        },
                        {
                            "title": "B. Espera e aprovação",
                            "items": [
                                item("cli-wait-1", "Período de seleção", "Empreendedora aguarda; sem acesso ao curso.", "Entre inscrição e comunicação", "MVP"),
                                item("cli-wait-2", "Resultado da seleção", "Comunicação de aprovada ou não aprovada.", "Fim da seleção", "MVP", "2.4.2.6"),
                                item("cli-wait-3", "Início jornada online", "Após aprovação, módulos liberados automaticamente em sequência.", "Pós-comunicação (online)", "MVP", "2.3.3.0"),
                                item("cli-wait-4", "Início jornada presencial/híbrida", "Convite ao grupo da turma; participação efetivada ao entrar no grupo.", "Pós-comunicação (P/H)", "MVP", "2.6.4"),
                            ],
                        },
                        {
                            "title": "C. Realização do curso (tipos de atividade)",
                            "items": CLI_TIPOS + [
                                item("2.5.2.1", "Home com progresso", "Visão dos módulos e percentual concluído.", "Durante o curso", "MVP", "2.5.2.1"),
                            ],
                        },
                        {
                            "title": "D. Conclusão e doação",
                            "items": [
                                item("2.5.2.4", "Certificados", "Consulta e solicitação quando atingir o percentual da edição.", "Após beneficiamento", "MVP", "2.5.2.4"),
                                item("2.5.1.6", "Acesso por link mágico", "Retorno ao app sem senha, por WhatsApp ou e-mail.", "Sempre", "MVP", "2.5.1.6"),
                                item(
                                    "cli-doacao-on-100",
                                    "Doação online — atingir 100% das atividades",
                                    "Concluir todas as atividades da edição para poder entrar na live de encerramento.",
                                    "Fim da formação online",
                                    "MVP",
                                    "2.5.2.1",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "cli-doacao-on-live",
                                    "Doação online — participar da live",
                                    "Abrir a live no YouTube (StreamYard; fora da plataforma). Só quem fez 100%.",
                                    "Fim da formação online",
                                    "MVP",
                                    "2.5.3.9",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "cli-doacao-on-kw",
                                    "Doação online — presença (palavra-chave)",
                                    "Após a live: atividade de presença com KW (case/acento-insensitive; prazo rígido; timestamp).",
                                    "Após a live",
                                    "MVP",
                                    "2.5.3.4",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "cli-doacao-on-quiz",
                                    "Doação online — questionário 100% certo",
                                    "Responder o questionário final só após KW válida; só 100% de acertos libera para doação.",
                                    "Após a palavra-chave",
                                    "MVP",
                                    "2.5.3.4",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "cli-status-ux",
                                    "Status humanizados na home",
                                    "Rótulos: inscrita / aguardando seleção ou entrevista / aprovada / ativa / concluída — evitar “matriculada”. WhatsApp = canal principal de aviso.",
                                    "Contínuo",
                                    "MVP",
                                    "2.5.1.1",
                                    plano_original=False,
                                ),
                                item(
                                    "cli-pos-pix",
                                    "Pós-liberação — indicar conta ou PIX",
                                    "Informar onde deseja receber (CPF-PIX imutável se chave = CPF); se material, endereço com ponto de referência.",
                                    "Após liberada para doação",
                                    "MVP",
                                    "2.5.2.4",
                                    capacidade=CAP_POS_DOACAO,
                                    capacidade_label=CAP_POS_DOACAO_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "cli-pos-recibo",
                                    "Pós-liberação — assinar recibo e aceites",
                                    "Visualizar itens da doação; assinar recibo (obrigatório; texto até 60 dias) e aceites. Material: só após confirmar recebimento.",
                                    "Após liberada para doação",
                                    "MVP",
                                    "2.5.2.4",
                                    capacidade=CAP_POS_DOACAO,
                                    capacidade_label=CAP_POS_DOACAO_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                            ],
                        },
                    ],
                },
                {
                    "id": "art-backend",
                    "title": "Retaguarda — motor de regras",
                    "desc": "Regras automáticas, integrações e proteção de dados — invisível à empreendedora, essencial ao ciclo.",
                    "blocks": [
                        {
                            "title": "Regras e segurança",
                            "items": [
                                item(
                                    "2.3.2.3-bloqueio",
                                    "Validação de bloqueios na inscrição",
                                    "Impedir cadastro quando idade ou disponibilidade presencial não atendem a regra da edição.",
                                    "Na inscrição",
                                    "MVP",
                                    "2.3.2.3",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "2.3.2.3-score",
                                    "Cálculo do score X/Y",
                                    "Calcular quantos critérios ativos da régua a inscrita atende, para apoiar a classificação no Gestor.",
                                    "Na inscrição",
                                    "MVP",
                                    "2.3.2.3",
                                    capacidade=CAP_CLASSIFICAR,
                                    capacidade_label=CAP_CLASSIFICAR_LABEL,
                                    capacidade_parte="extensao",
                                ),
                                item(
                                    "be-cadastro-persistir",
                                    "Persistir inscrição, empreendedora e empreendimento",
                                    "Núcleo: gravar inscrição completa, criar empreendedora e empreendimento vinculados, UUID de dispositivo e status em seleção.",
                                    "Ao concluir o cadastro",
                                    "MVP",
                                    "2.3.2.3",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "be-cadastro-schema",
                                    "Schema e respostas dinâmicas da inscrição",
                                    "Extensão: API do schema da edição; validação server-side; snapshot da definição no submit; respostas tipadas (JSON/EAV) sem misturar perguntas variáveis ao BI comparável. Alinha retomada e alerta de inscrição incompleta.",
                                    "Na inscrição",
                                    "MVP",
                                    "2.3.2.3",
                                    capacidade=CAP_CADASTRO,
                                    capacidade_label=CAP_CADASTRO_LABEL,
                                    capacidade_parte="extensao",
                                    impacta_modelo=True,
                                ),
                                item(
                                    "be-entrevista-modelo",
                                    "Modelo de dados — entrevista de seleção",
                                    "Extensão: sessões (data, hora, local, capacidade), alocação de qualificadas, presença/ausência, decisão aprovar/não aprovar, realocação e CSV de presença. Status ausente → não aprovada (auto). Alimenta travas do Comunicar (convite só com sessão; liberação só com turma).",
                                    "Seleção P/H",
                                    "MVP",
                                    "2.4.2.4",
                                    capacidade=CAP_ENTREVISTA,
                                    capacidade_label=CAP_ENTREVISTA_LABEL,
                                    capacidade_parte="extensao",
                                    impacta_modelo=True,
                                ),
                                item("2.3.1.2", "Links de acesso seguros", "Empreendedora e gestor entram sem senha, por link personalizado.", "Login", "MVP", "2.3.1.2"),
                                item("2.3.4.1", "Cálculo de beneficiamento e certificado", "Automático conforme % da edição.", "Encerramento", "MVP", "2.3.4.1"),
                                item(
                                    "be-doacao-on-funil",
                                    "Doação online — regras do funil",
                                    "Bloquear live sem 100%; validar palavra-chave; liberar doação só com questionário 100% certo; gravar timestamp do quiz.",
                                    "Fim da formação online",
                                    "MVP",
                                    "2.3.4.1",
                                    capacidade=CAP_DOACAO_ON,
                                    capacidade_label=CAP_DOACAO_ON_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "be-doacao-itens",
                                    "Doação — persistir itens 1:N",
                                    "Extensão: modelo e API para N linhas (produto + valor) por doação. Impacta modelo.",
                                    "Operação de doação",
                                    "MVP",
                                    "2.3.4.1",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                    impacta_modelo=True,
                                ),
                                item(
                                    "be-orcamento-unidade",
                                    "Orçamento por unidade — regras e log",
                                    "Extensão: teto por unidade definido no CMS (UC9); validar consumo na aprovação (UC57); saldos por unidade. Impacta modelo.",
                                    "Configuração e operação",
                                    "MVP",
                                    "2.3.4.1",
                                    capacidade=CAP_DOACAO_PH,
                                    capacidade_label=CAP_DOACAO_PH_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                    impacta_modelo=True,
                                ),
                                item(
                                    "be-pos-doacao",
                                    "Pós-liberação — persistir PIX, recibo e aceites",
                                    "Guardar dados bancários (CPF-PIX imutável), itens no recibo, assinatura obrigatória e aceites; copy até 60 dias.",
                                    "Após liberada para doação",
                                    "MVP",
                                    "2.3.4.1",
                                    capacidade=CAP_POS_DOACAO,
                                    capacidade_label=CAP_POS_DOACAO_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item("2.2.14", "Proteção de dados (LGPD)", "Consentimentos, anonimização de não aprovadas.", "Contínuo", "Fase 2", "2.2.14"),
                            ],
                        },
                        {
                            "title": "Regras por tipo de atividade",
                            "items": BE_TIPOS + [
                                item(
                                    "be-tipo-beneficiamento",
                                    "Toda atividade liberada conta no beneficiamento",
                                    "Não há tipo 'que não beneficia': o percentual de conclusão considera todas as atividades liberadas na edição.",
                                    "Durante o curso",
                                    "MVP",
                                    "2.2.8",
                                ),
                            ],
                        },
                        {
                            "title": "Jornada online e mensagens",
                            "items": [
                                item("2.3.3.0", "Liberação automática da jornada online", "Após aprovação, módulos liberados em sequência; confirmação OK da empreendedora. Fila de jornada (≠ fila de alertas).", "Pós-comunicação online", "MVP", "2.3.3.0"),
                                item("2.3.5.2", "Integração WhatsApp", "Templates de inscrição, aprovação e atividades. Download: template + arquivos no WhatsApp após OK (também no Cliente).", "Inscrição e jornada", "MVP", "2.3.5.2"),
                                item("2.3.5.4", "Disparo após comunicar aprovação", "Primeiro gatilho da jornada online.", "Fim da seleção", "MVP", "2.3.5.4"),
                                item("2.3.5.1", "E-mail transacional", "Links de acesso e comunicações por e-mail.", "Contínuo", "MVP", "2.3.5.1"),
                                item(
                                    "be-fila-alertas",
                                    "Fila de alertas (engajamento)",
                                    "Avaliar regras UC87, respeitar cadência/exitWhen, enviar via SendGrid/Gupshup. Substitui Mautic.",
                                    "Contínuo",
                                    "MVP",
                                    "2.3.5.7",
                                    capacidade=CAP_ALERTAS,
                                    capacidade_label=CAP_ALERTAS_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                                item(
                                    "be-alertas-eval",
                                    "Avaliador de métricas de alerta",
                                    "Job + eventos: inscrição incompleta, prazo, backlog, fim de edição, risco curto, check-point.",
                                    "Contínuo",
                                    "MVP",
                                    "2.3.5.7",
                                    capacidade=CAP_ALERTAS,
                                    capacidade_label=CAP_ALERTAS_LABEL,
                                    capacidade_parte="extensao",
                                    plano_original=False,
                                ),
                                item("2.3.5.5", "Envio de vídeo por WhatsApp", "Complemento opcional na jornada online: arquivo compatível com WhatsApp, além do consumo oficial na plataforma.", "Durante curso online", "Fase 2", "2.3.5.5", capacidade="tipo-video-aula", capacidade_label="Vídeo Aula", capacidade_parte="extensao", plano_original=False),
                            ],
                        },
                    ],
                },
                {
                    "id": "art-comunicacao",
                    "title": "Comunicação e WhatsApp",
                    "desc": "Eventos de mensagem que conectam inscrição, seleção e jornada — templates via pacotes UC88.",
                    "blocks": [
                        {
                            "title": "Fluxos de comunicação",
                            "items": [
                                item("2.6.1", "Seleção de pacote na edição (UC9)", "Admin escolhe **PacoteComunicacao** (UC88) na edição; snapshot na publicação. Substitui templates inline por edição.", "Configuração por edição", "MVP", "2.6.1", plano_original=False),
                                item("2.6.2", "Primeiro contato pós-cadastro", "Empreendedora escreve no número da organização; sistema responde (template do pacote).", "Após inscrição completa", "MVP", "2.6.2"),
                                item("2.6.3", "Comunicar aprovação/reprovação", "Disparo do resultado da seleção (UC25 — inicia jornada das aptas).", "Fim da seleção", "MVP", "2.6.3"),
                                item("2.6.5", "Jornada online — liberar / OK / lote", "Mecânica de liberação e lembretes (UC33).", "Durante curso online", "MVP", "2.6.5"),
                                item("2.6.6", "Alertas de risco de evasão", "Mensagens automáticas UC87/UC53 para quem parou na jornada online.", "Durante curso online", "Fase 2", "2.6.6", plano_original=False),
                            ],
                        },
                        {
                            "title": "Mensageria por tipo de atividade",
                            "items": MSG_TIPOS,
                        },
                    ],
                },
                {
                    "id": "art-bi",
                    "title": "BI e indicadores",
                    "desc": "Painel de Dados (Looker Studio): impacto institucional, funil executivo e relatórios — separados da visão operacional do App Gestor.",
                    "blocks": [
                        {
                            "title": "Escopo contemplado — visão executiva",
                            "items": [
                                item(
                                    "2.7.1",
                                    "Funil executivo — inscritas, selecionadas, iniciaram, concluíram",
                                    "KPIs do dashboard C-level: inscritas → selecionadas → iniciaram → concluíram (beneficiadas / certificadas). Distinto dos totais operacionais do App Gestor.",
                                    "Durante e após edição",
                                    "Fase 2",
                                    "2.7.1",
                                ),
                                item(
                                    "2.7.5",
                                    "Evolução de renda e faturamento",
                                    "Núcleo: séries e consolidado de **renda** e **faturamento** a partir dos registros aprovados — visão executiva do Painel de Dados.",
                                    "Durante e após edição",
                                    "MVP",
                                    "2.7.3",
                                    capacidade="tipo-faturamento",
                                    capacidade_label="Registro de faturamento",
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "bi-perfil-socioeconomico",
                                    "Perfil socioeconômico por programa",
                                    "Relatórios qualitativos consolidados: gênero, raça/cor (recorte negras IBGE), idade, filhos, escolaridade e demais campos comparáveis — por programa e edição.",
                                    "Durante e após edição",
                                    "Fase 2",
                                    "2.7.3",
                                ),
                                item(
                                    "2.7.2",
                                    "Dashboard visual de impacto social",
                                    "Painel Looker Studio ligado ao banco: KPIs, filtros (programa, edição, região, UF, município) e comparativos com base legada (UC59).",
                                    "Pós-piloto",
                                    "Fase 2",
                                    "2.7.2",
                                ),
                                item(
                                    "2.7.6",
                                    "NPS e pesquisas de avaliação",
                                    "Consolidado de NPS (promotoras, neutras, detratoras) e demais pesquisas de avaliação (aulas, formato do curso, pós-programa UC82) por edição e programa.",
                                    "Encerramento",
                                    "Fase 2",
                                    "2.7.3",
                                    capacidade="tipo-nps",
                                    capacidade_label="NPS",
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "2.7.3",
                                    "Relatório como artefato",
                                    "Geração de relatórios exportáveis (quantitativos e qualitativos) para prestação de contas — disponível na visão executiva e também fora dela (UC60/UC61).",
                                    "Contínuo",
                                    "Fase 2",
                                    "2.7.3",
                                ),
                                item(
                                    "bi-serie-anual",
                                    "Série anual",
                                    "Evolução anual dos indicadores (funil, renda, faturamento, NPS) — agregação por ano de competência ou série histórica durante o projeto.",
                                    "Contínuo",
                                    "Fase 2",
                                    "2.7.3",
                                ),
                            ],
                        },
                        {
                            "title": "Escopo contemplado — fora do executivo",
                            "items": [
                                item(
                                    "2.7.4",
                                    "Frequência e participação",
                                    "Quem fez / não fez por tipo de atividade: presença, vídeo, tarefas, downloads, questionários. Base operacional dos relatórios de participação — não entra no dashboard C-level.",
                                    "Durante e após edição",
                                    "MVP",
                                    "2.7.1",
                                ),
                                item(
                                    "bi-investimento-poupanca",
                                    "Investimento e poupança",
                                    "Séries e consolidado de **investimento** e **poupança** a partir dos registros aprovados — contemplado no RFP, fora da visão executiva resumida.",
                                    "Durante e após edição",
                                    "MVP",
                                    "2.7.3",
                                    capacidade="tipo-faturamento",
                                    capacidade_label="Registro de faturamento",
                                    capacidade_parte="nucleo",
                                ),
                                item(
                                    "bi-relatorio-beneficiaria",
                                    "Relatório por beneficiária",
                                    "Ficha consolidada por empreendedora: perfil, frequência, evolução financeira, NPS e histórico de participação — drill-down operacional.",
                                    "Durante e após edição",
                                    "Fase 2",
                                    "2.7.3",
                                ),
                            ],
                        },
                        {
                            "title": "Além do escopo",
                            "items": [
                                item(
                                    "bi-metas-institucionais",
                                    "Metas institucionais e prazos contratuais",
                                    "Painel de metas da organização e marcos contratuais (beneficiamento, certificação, doação) com prazos e % de cumprimento por edição/programa.",
                                    "Contínuo",
                                    "Fase 3",
                                ),
                                item(
                                    "bi-capital-semente-doacoes",
                                    "Capital semente e doações",
                                    "Consolidado de capital semente concedido: valor, modalidade, beneficiárias e empreendimentos contemplados — visão financeira de impacto.",
                                    "Durante e após edição",
                                    "Fase 3",
                                ),
                                item(
                                    "bi-mapa-regioes",
                                    "Mapa de regiões",
                                    "Visualização geográfica de participantes e impacto por UF, município e região — gráficos e mapa interativo no Painel de Dados.",
                                    "Durante e após edição",
                                    "Fase 3",
                                ),
                                item(
                                    "bi-mentorias",
                                    "Acompanhamento das mentorias",
                                    "Indicadores de mentorias registradas: sessões, horas, mentores e empreendedoras atendidas por edição/unidade.",
                                    "Durante e após edição",
                                    "Fase 3",
                                ),
                                item(
                                    "bi-tipos-doacao-valores",
                                    "Tipos de doação e valores",
                                    "Breakdown por tipo de doação (capital semente, material, etc.) e valores concedidos — consolidado para prestação de contas.",
                                    "Durante e após edição",
                                    "Fase 3",
                                ),
                                item(
                                    "bi-pessoas-empreendimentos",
                                    "Divisão empreendedoras e empreendimentos",
                                    "Contagem dupla UC71: N empreendedoras (beneficiadas, certificadas, ativas) × 1 empreendimento × 1 doação por negócio coletivo.",
                                    "Durante e após edição",
                                    "Fase 2",
                                ),
                                item(
                                    "bi-analise-persona",
                                    "Análise de Persona",
                                    "Persona representativa gerada a partir dos filtros do dashboard (perfil demográfico e socioeconômico médio da seleção).",
                                    "Durante e após edição",
                                    "Fase 3",
                                ),
                            ],
                        },
                        {
                            "title": "Extensões — registro de faturamento",
                            "items": [
                                item(
                                    "bi-tipo-faturamento-7",
                                    "Evolução econômica — 7 indicadores",
                                    "Extensão: séries e consolidado também com despesas fixas, nº de clientes e nº de produtos vendidos.",
                                    "Durante e após edição",
                                    "MVP",
                                    "2.7.3",
                                    capacidade="tipo-faturamento",
                                    capacidade_label="Registro de faturamento",
                                    capacidade_parte="extensao",
                                ),
                                item(
                                    "bi-tipo-faturamento-dificuldade",
                                    "Evolução econômica — dificuldade de preenchimento",
                                    "Extensão: distribuição da autoavaliação de dificuldade (5 níveis) por turma/edição — indicador qualitativo de aderência ao reporte.",
                                    "Durante e após edição",
                                    "MVP",
                                    "2.7.3",
                                    capacidade="tipo-faturamento",
                                    capacidade_label="Registro de faturamento",
                                    capacidade_parte="extensao",
                                ),
                            ],
                        },
                    ],
                },
                {
                    "id": "art-alertas",
                    "title": "Alertas de engajamento",
                    "desc": "Regras tipadas no CMS, binding no Gestor, fila no Backend (SendGrid + Gupshup). Mautic removido do projeto.",
                    "blocks": [
                        {
                            "title": "Capacidade transversal",
                            "items": [
                                item(
                                    "alertas-resumo",
                                    "Duas filas de comunicação",
                                    "Fila jornada (UC33 OK/lote) ≠ fila alertas (UC87). Mesma janela comercial WhatsApp; templates distintos.",
                                    "Arquitetura",
                                    "MVP",
                                    capacidade=CAP_ALERTAS,
                                    capacidade_label=CAP_ALERTAS_LABEL,
                                    capacidade_parte="nucleo",
                                    plano_original=False,
                                ),
                            ],
                        },
                    ],
                },
                {
                    "id": "art-infra",
                    "title": "Infraestrutura",
                    "desc": "Ambientes onde o sistema roda com segurança.",
                    "blocks": [
                        {
                            "title": "Ambientes",
                            "items": [
                                item("2.1.1", "Homologação", "Ambiente de testes antes de produção.", "Durante desenvolvimento", "MVP", "2.1.1", 70),
                                item("2.1.2", "Produção", "Ambiente oficial para edições reais.", "Go-live", "MVP", "2.1.2"),
                                item("2.1.3", "Publicação automatizada", "Deploy seguro de novas versões.", "Contínuo", "MVP", "2.1.3"),
                            ],
                        },
                    ],
                },
            ],
        },
        {
            "id": "phase-implementacao",
            "title": "Implementação",
            "desc": "Colocar em operação, capacitar equipe e concluir o primeiro ciclo completo com edições piloto.",
            "artifacts": [
                {
                    "id": "art-impl-op",
                    "title": "Operação e piloto",
                    "desc": "Da preparação ao primeiro ciclo fechado com beneficiamento e doação.",
                    "blocks": [
                        {
                            "title": "Ciclo piloto",
                            "items": [
                                item("imp-1", "Conteúdo pedagógico no CMS", "Vídeos, questionários e materiais da edição piloto cadastrados.", "Antes de abrir inscrições", "MVP"),
                                item("imp-2", "Capacitação da equipe", "Gestores de unidade e turma treinados nos fluxos.", "Antes do go-live", "MVP", "2.8.2"),
                                item("imp-3", "Piloto — 1 edição online + 1 P/H", "Duas edições reais cobrindo os dois modelos de jornada.", "Implementação", "MVP"),
                                item("imp-4", "Homologação com gestores reais", "Validação em ambiente de testes com usuários finais.", "Pré go-live", "MVP", "2.8.2"),
                                item("imp-5", "Go-live — inscrições abertas", "Primeira edição aberta ao público.", "Implementação", "MVP"),
                                item("imp-6", "Acompanhamento semanal do ciclo", "Seleção → curso → encerramento → doação.", "Durante piloto", "MVP"),
                                item("2.8.1", "Testes do ciclo completo", "Inscrição até doação em ambiente integrado.", "Pré piloto", "MVP", "2.8.1"),
                                item("2.8.3", "Ajustes pós-piloto", "Melhorias após primeira edição.", "Após piloto", "Fase 2", "2.8.3"),
                            ],
                        },
                    ],
                },
            ],
        },
    ],
}

ESTRUTURA_OUT.write_text(
    json.dumps(ESTRUTURA, ensure_ascii=False, indent=2), encoding="utf-8"
)

# index.html is maintained as source file; build only regenerates estrutura.json
print(f"Gerado: {ESTRUTURA_OUT}")
