"""Gera Estrutura_Evolucao_Projeto.csv a partir da estrutura definida."""
import csv

ROWS = [
    ("1", "", "Levantamento", "Levantamento requisitos e prototipação", 0, "Grupo", 1, "", "Agora", "", ""),
    ("1.1", "1", "Levantamento", "Use Cases (v6)", 1, "Folha", 1, "70", "Agora", "v6", ""),
    ("1.2", "1", "Levantamento", "Tipos de Atividade", 1, "Folha", 1, "", "Agora", "UC15", ""),
    ("1.3", "1", "Levantamento", "Modelo de dados / entidades", 1, "Folha", 1, "", "Agora", "", ""),
    ("1.4", "1", "Levantamento", "Validação Protótipo Gestor", 1, "Folha", 1, "80", "Agora", "UC3+", ""),
    ("1.5", "1", "Levantamento", "Validação Protótipo Admin (CMS)", 1, "Folha", 1, "80", "Agora", "UC1–UC15", ""),
    ("1.6", "1", "Levantamento", "Validação Protótipo Cliente", 1, "Folha", 1, "", "Agora", "UC19–UC21", ""),
    ("1.7", "1", "Levantamento", "Design system / Design.md", 1, "Folha", 1, "", "Agora", "", ""),
    ("2", "", "Desenvolvimento", "Desenvolvimento", 0, "Grupo", 1, "", "", "", ""),
    ("2.1", "2", "Desenvolvimento", "Infraestrutura", 1, "Grupo", 1, "", "", "", ""),
    ("2.1.1", "2.1", "Desenvolvimento", "Ambientes de Homologação", 2, "Folha", 1, "70", "Agora", "", ""),
    ("2.1.2", "2.1", "Desenvolvimento", "Ambiente de Produção", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.1.3", "2.1", "Desenvolvimento", "CI/CD e deploy", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.1.4", "2.1", "Desenvolvimento", "Armazenamento mídia (vídeos, uploads)", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.1.5", "2.1", "Desenvolvimento", "Monitoramento / logs básicos", 2, "Folha", 1, "", "Fase 2", "", ""),
    ("2.2", "2", "Desenvolvimento", "Sistema Administrativo (CMS)", 1, "Grupo", 1, "70", "Agora", "", "% inicial agregado; migrar para fórmula ao preencher filhos"),
    ("2.2.1", "2.2", "Desenvolvimento", "Login e autenticação admin", 2, "Folha", 1, "", "MVP", "UC2, UC6", ""),
    ("2.2.2", "2.2", "Desenvolvimento", "Colaboradores e roles", 2, "Folha", 1, "", "MVP", "UC1, UC5", ""),
    ("2.2.3", "2.2", "Desenvolvimento", "Cadastro de Programa", 2, "Folha", 1, "", "MVP", "UC7", ""),
    ("2.2.4", "2.2", "Desenvolvimento", "Cadastro de Edição", 2, "Folha", 1, "", "MVP", "UC9", ""),
    ("2.2.5", "2.2", "Desenvolvimento", "Unidades", 2, "Folha", 1, "", "MVP", "UC66", ""),
    ("2.2.6", "2.2", "Desenvolvimento", "Módulos temáticos + tipos de atividade", 2, "Folha", 1, "", "MVP", "UC15", ""),
    ("2.2.7", "2.2", "Desenvolvimento", "Régua elegibilidade (bloqueio + 6 critérios)", 2, "Folha", 1, "", "MVP", "UC12", ""),
    ("2.2.8", "2.2", "Desenvolvimento", "Beneficiamento e certificação (% edição)", 2, "Folha", 1, "", "MVP", "UC13", ""),
    ("2.2.9", "2.2", "Desenvolvimento", "Encerrar edição (freeze)", 2, "Folha", 1, "", "MVP", "UC81", ""),
    ("2.2.10", "2.2", "Desenvolvimento", "Organizações / patrocinadores", 2, "Folha", 1, "", "Fase 2", "UC10, UC11", ""),
    ("2.2.11", "2.2", "Desenvolvimento", "Elegibilidade doação A–D", 2, "Folha", 1, "", "Fase 2", "UC14", ""),
    ("2.2.12", "2.2", "Desenvolvimento", "Pesquisa pós-programa (formulário)", 2, "Folha", 1, "", "Fase 2", "UC82", ""),
    ("2.2.13", "2.2", "Desenvolvimento", "Voluntários / mentores", 2, "Folha", 1, "", "Fase 2", "UC73", ""),
    ("2.2.14", "2.2", "Desenvolvimento", "Anonimização LGPD", 2, "Folha", 1, "", "Fase 2", "UC76", ""),
    ("2.3", "2", "Desenvolvimento", "Backend", 1, "Grupo", 1, "20", "", "", "% inicial agregado"),
    ("2.3.1", "2.3", "Desenvolvimento", "Core e autenticação", 2, "Grupo", 1, "", "", "", ""),
    ("2.3.1.1", "2.3.1", "Desenvolvimento", "Modelo de dados e migrations", 3, "Folha", 1, "", "Agora", "", ""),
    ("2.3.1.2", "2.3.1", "Desenvolvimento", "Link mágico empreendedora", 3, "Folha", 1, "", "MVP", "UC4, UC54", ""),
    ("2.3.1.3", "2.3.1", "Desenvolvimento", "Link mágico gestor", 3, "Folha", 1, "", "MVP", "UC3", ""),
    ("2.3.1.4", "2.3.1", "Desenvolvimento", "UUID dispositivo / sessão", 3, "Folha", 1, "", "MVP", "UC67", ""),
    ("2.3.1.5", "2.3.1", "Desenvolvimento", "CPF HMAC + pepper", 3, "Folha", 1, "", "MVP", "UC6", ""),
    ("2.3.2", "2.3", "Desenvolvimento", "Inscrição e seleção", 2, "Grupo", 1, "", "", "", ""),
    ("2.3.2.1", "2.3.2", "Desenvolvimento", "Pré-cadastro e aceites LGPD/WhatsApp", 3, "Folha", 1, "", "MVP", "UC19, UC20", ""),
    ("2.3.2.2", "2.3.2", "Desenvolvimento", "Inscrição completa (4 blocos)", 3, "Folha", 1, "", "MVP", "UC21", ""),
    ("2.3.2.3", "2.3.2", "Desenvolvimento", "Validação elegibilidade automática", 3, "Folha", 1, "", "MVP", "UC23", ""),
    ("2.3.2.4", "2.3.2", "Desenvolvimento", "Classificação status participante", 3, "Folha", 1, "", "MVP", "UC29", ""),
    ("2.3.2.5", "2.3.2", "Desenvolvimento", "Export/import CSV seleção", 3, "Folha", 1, "", "MVP", "UC24", ""),
    ("2.3.2.6", "2.3.2", "Desenvolvimento", "Histórico legado / recorrente", 3, "Folha", 1, "", "Fase 3", "UC22", ""),
    ("2.3.3", "2.3", "Desenvolvimento", "Tipos de atividade — regras API", 2, "Grupo", 1, "", "", "", ""),
    ("2.3.3.0", "2.3.3", "Desenvolvimento", "Orquestração jornada online (temporizador, OK, lote)", 3, "Folha", 1, "", "MVP", "UC33", ""),
    ("2.3.3.1", "2.3.3", "Desenvolvimento", "Tipo — Evento Presencial", 3, "Folha", 1, "", "MVP", "UC40, UC41", ""),
    ("2.3.3.2", "2.3.3", "Desenvolvimento", "Tipo — Vídeo Aula", 3, "Folha", 1, "", "MVP", "UC37", ""),
    ("2.3.3.3", "2.3.3", "Desenvolvimento", "Tipo — Questionário Inicial", 3, "Folha", 1, "", "MVP", "UC39", ""),
    ("2.3.3.4", "2.3.3", "Desenvolvimento", "Tipo — Questionário Final", 3, "Folha", 1, "", "MVP", "UC39", ""),
    ("2.3.3.5", "2.3.3", "Desenvolvimento", "Tipo — Tarefa de Casa", 3, "Folha", 1, "", "MVP", "UC43, UC44", ""),
    ("2.3.3.6", "2.3.3", "Desenvolvimento", "Tipo — Download de Conteúdo", 3, "Folha", 1, "", "MVP", "UC36", ""),
    ("2.3.3.7", "2.3.3", "Desenvolvimento", "Tipo — Registro de Faturamento", 3, "Folha", 1, "", "MVP", "UC45", ""),
    ("2.3.3.8", "2.3.3", "Desenvolvimento", "Tipo — Atividade (questionário genérico)", 3, "Folha", 1, "", "Fase 2", "UC39", ""),
    ("2.3.3.9", "2.3.3", "Desenvolvimento", "Tipo — Aula ao Vivo", 3, "Folha", 1, "", "Fase 2", "UC38", ""),
    ("2.3.3.10", "2.3.3", "Desenvolvimento", "Tipo — Plano de Ação", 3, "Folha", 1, "", "Fase 2", "UC39", ""),
    ("2.3.3.11", "2.3.3", "Desenvolvimento", "Tipo — Visita Técnica", 3, "Folha", 1, "", "Fase 2", "UC78", ""),
    ("2.3.3.12", "2.3.3", "Desenvolvimento", "Tipo — NPS", 3, "Folha", 1, "", "Fase 2", "UC39", ""),
    ("2.3.4", "2.3", "Desenvolvimento", "Beneficiamento e certificado", 2, "Grupo", 1, "", "", "", ""),
    ("2.3.4.1", "2.3.4", "Desenvolvimento", "Cálculo beneficiamento / certificado automático", 3, "Folha", 1, "", "MVP", "UC55", ""),
    ("2.3.4.2", "2.3.4", "Desenvolvimento", "Desligamento empreendedora", 3, "Folha", 1, "", "Fase 2", "UC79", ""),
    ("2.3.5", "2.3", "Desenvolvimento", "Comunicação (integrações backend)", 2, "Grupo", 1, "", "", "", ""),
    ("2.3.5.1", "2.3.5", "Desenvolvimento", "Integração SendGrid", 3, "Folha", 1, "", "MVP", "UC54", ""),
    ("2.3.5.2", "2.3.5", "Desenvolvimento", "Integração Gupshup (WhatsApp)", 3, "Folha", 1, "", "MVP", "UC49", ""),
    ("2.3.5.3", "2.3.5", "Desenvolvimento", "Template pós-cadastro (usuária escreve primeiro)", 3, "Folha", 1, "", "MVP", "inscrição", ""),
    ("2.3.5.4", "2.3.5", "Desenvolvimento", "Disparo pós-comunicar aprovação", 3, "Folha", 1, "", "MVP", "UC25, UC33", ""),
    ("2.3.5.5", "2.3.5", "Desenvolvimento", "Envio vídeo via WhatsApp (online)", 3, "Folha", 1, "", "Fase 2", "UC51", ""),
    ("2.3.5.6", "2.3.5", "Desenvolvimento", "Lembretes inscrição incompleta (alerta UC87 + manual UC26)", 3, "Folha", 1, "", "MVP", "UC26/UC87", ""),
    ("2.3.5.7", "2.3.5", "Desenvolvimento", "Fila de alertas Backend (ex-Mautic)", 3, "Folha", 1, "", "MVP", "UC52/UC87", ""),
    ("2.4", "2", "Desenvolvimento", "Aplicativo Gestor", 1, "Grupo", 1, "10", "", "", "% inicial agregado"),
    ("2.4.1", "2.4", "Desenvolvimento", "Comum", 2, "Grupo", 1, "", "", "", ""),
    ("2.4.1.1", "2.4.1", "Desenvolvimento", "Login link mágico", 3, "Folha", 1, "", "MVP", "UC3", ""),
    ("2.4.1.2", "2.4.1", "Desenvolvimento", "Dashboard de edições", 3, "Folha", 1, "", "MVP", "UC3", ""),
    ("2.4.1.3", "2.4.1", "Desenvolvimento", "Layout e navegação por edição", 3, "Folha", 1, "", "MVP", "", ""),
    ("2.4.1.4", "2.4.1", "Desenvolvimento", "Home operacional / KPIs", 3, "Folha", 1, "", "MVP", "", ""),
    ("2.4.2", "2.4", "Desenvolvimento", "Seleção (Gestor Unidade)", 2, "Grupo", 1, "", "", "", ""),
    ("2.4.2.1", "2.4.2", "Desenvolvimento", "Classificar inscrições (score X/Y)", 3, "Folha", 1, "", "MVP", "UC24", ""),
    ("2.4.2.2", "2.4.2", "Desenvolvimento", "Export CSV inscritas", 3, "Folha", 1, "", "MVP", "UC24", ""),
    ("2.4.2.3", "2.4.2", "Desenvolvimento", "Agrupar empreendimento (modal)", 3, "Folha", 1, "", "MVP", "UC31", ""),
    ("2.4.2.4", "2.4.2", "Desenvolvimento", "Oficina presencial (etapa 2)", 3, "Folha", 1, "", "Fase 2", "UC84", ""),
    ("2.4.2.5", "2.4.2", "Desenvolvimento", "Alocar turma (etapa 3)", 3, "Folha", 1, "", "MVP", "UC17", ""),
    ("2.4.2.6", "2.4.2", "Desenvolvimento", "Comunicar resultado da seleção", 3, "Folha", 1, "", "MVP", "UC25", ""),
    ("2.4.2.7", "2.4.2", "Desenvolvimento", "Remanejar entre unidades/turmas", 3, "Folha", 1, "", "Fase 2", "UC18", ""),
    ("2.4.2.8", "2.4.2", "Desenvolvimento", "Histórico de participação", 3, "Folha", 1, "", "Fase 2", "UC28", ""),
    ("2.4.2.9", "2.4.2", "Desenvolvimento", "Mini CRM — leads incompletos", 3, "Folha", 1, "", "Fase 2", "UC26", ""),
    ("2.4.3", "2.4", "Desenvolvimento", "Operação (Gestor Turma)", 2, "Grupo", 1, "", "", "", ""),
    ("2.4.3.1", "2.4.3", "Desenvolvimento", "CRUD turmas + link grupo WhatsApp", 3, "Folha", 1, "", "MVP", "UC16", ""),
    ("2.4.3.2", "2.4.3", "Desenvolvimento", "Lista / detalhe participante", 3, "Folha", 1, "", "MVP", "UC27", ""),
    ("2.4.3.3", "2.4.3", "Desenvolvimento", "Editar participante / inserir dados em nome", 3, "Folha", 1, "", "Fase 2", "UC69", ""),
    ("2.4.3.4", "2.4.3", "Desenvolvimento", "Cancelamento / desistência", 3, "Folha", 1, "", "Fase 2", "UC30", ""),
    ("2.4.3.5", "2.4.3", "Desenvolvimento", "Lista de negócios + detalhe", 3, "Folha", 1, "", "MVP", "UC31", ""),
    ("2.4.3.6", "2.4.3", "Desenvolvimento", "Liberar atividades por tipo (P/H)", 3, "Folha", 1, "", "MVP", "UC34", ""),
    ("2.4.3.7", "2.4.3", "Desenvolvimento", "Acompanhar progresso (online)", 3, "Folha", 1, "", "MVP", "UC34, UC56", ""),
    ("2.4.3.8", "2.4.3", "Desenvolvimento", "Presença manual + QR encontro", 3, "Folha", 1, "", "MVP", "UC41", ""),
    ("2.4.3.9", "2.4.3", "Desenvolvimento", "Fila aprovar/revisar tarefa e faturamento", 3, "Folha", 1, "", "MVP", "UC44", ""),
    ("2.4.3.10", "2.4.3", "Desenvolvimento", "Facilitador WhatsApp grupo", 3, "Folha", 1, "", "MVP", "UC50", ""),
    ("2.4.3.11", "2.4.3", "Desenvolvimento", "Ranking e engajamento / risco evasão", 3, "Folha", 1, "", "Fase 2", "UC56, UC53", ""),
    ("2.4.3.12", "2.4.3", "Desenvolvimento", "Aula presencial extra", 3, "Folha", 1, "", "Fase 2", "UC35", ""),
    ("2.4.3.13", "2.4.3", "Desenvolvimento", "Relato de encontro / export presença", 3, "Folha", 1, "", "Fase 2", "UC80", ""),
    ("2.4.3.14", "2.4.3", "Desenvolvimento", "Visita técnica (calendário)", 3, "Folha", 1, "", "Fase 2", "UC78", ""),
    ("2.4.4", "2.4", "Desenvolvimento", "Encerramento e doação", 2, "Grupo", 1, "", "", "", ""),
    ("2.4.4.1", "2.4.4", "Desenvolvimento", "Encerrar edição (Gestor)", 3, "Folha", 1, "", "MVP", "UC81", ""),
    ("2.4.4.2", "2.4.4", "Desenvolvimento", "Sugerir doação (Turma)", 3, "Folha", 1, "", "MVP", "UC57", ""),
    ("2.4.4.3", "2.4.4", "Desenvolvimento", "Aprovar doação (Unidade)", 3, "Folha", 1, "", "MVP", "UC57", ""),
    ("2.4.4.4", "2.4.4", "Desenvolvimento", "Seleção elegíveis lote A–D", 3, "Folha", 1, "", "Fase 2", "UC85", ""),
    ("2.4.4.5", "2.4.4", "Desenvolvimento", "Dados bancários / PIX / recibo", 3, "Folha", 1, "", "Fase 2", "UC86", ""),
    ("2.4.4.6", "2.4.4", "Desenvolvimento", "Workshop encerramento", 3, "Folha", 1, "", "Fase 2", "", ""),
    ("2.4.4.7", "2.4.4", "Desenvolvimento", "Mentorias", 3, "Folha", 1, "", "Fase 2", "UC70", ""),
    ("2.4.4.8", "2.4.4", "Desenvolvimento", "Capital semente", 3, "Folha", 1, "", "Fase 3", "UC58", ""),
    ("2.5", "2", "Desenvolvimento", "Aplicativo Cliente (Educacional)", 1, "Grupo", 1, "0", "", "", ""),
    ("2.5.1", "2.5", "Desenvolvimento", "Inscrição", 2, "Grupo", 1, "", "", "", ""),
    ("2.5.1.1", "2.5.1", "Desenvolvimento", "Landing edição (slug) + UUID", 3, "Folha", 1, "", "MVP", "UC19, UC67", ""),
    ("2.5.1.2", "2.5.1", "Desenvolvimento", "Termos e consentimentos", 3, "Folha", 1, "", "MVP", "UC20", ""),
    ("2.5.1.3", "2.5.1", "Desenvolvimento", "Pré-cadastro", 3, "Folha", 1, "", "MVP", "UC19", ""),
    ("2.5.1.4", "2.5.1", "Desenvolvimento", "Inscrição — 4 blocos + régua", 3, "Folha", 1, "", "MVP", "UC21", ""),
    ("2.5.1.5", "2.5.1", "Desenvolvimento", "Confirmação + CTA WhatsApp", 3, "Folha", 1, "", "MVP", "UC21", ""),
    ("2.5.1.6", "2.5.1", "Desenvolvimento", "Login link mágico", 3, "Folha", 1, "", "MVP", "UC4", ""),
    ("2.5.2", "2.5", "Desenvolvimento", "Shell da jornada", 2, "Grupo", 1, "", "", "", ""),
    ("2.5.2.1", "2.5.2", "Desenvolvimento", "Home — módulos accordion + progresso", 3, "Folha", 1, "", "MVP", "UC36", ""),
    ("2.5.2.2", "2.5.2", "Desenvolvimento", "Calendário de atividades", 3, "Folha", 1, "", "Fase 2", "UC68", ""),
    ("2.5.2.3", "2.5.2", "Desenvolvimento", "Meu perfil / histórico", 3, "Folha", 1, "", "Fase 2", "", ""),
    ("2.5.2.4", "2.5.2", "Desenvolvimento", "Certificados", 3, "Folha", 1, "", "MVP", "UC63", ""),
    ("2.5.2.5", "2.5.2", "Desenvolvimento", "Solicitar desligamento", 3, "Folha", 1, "", "Fase 2", "UC79", ""),
    ("2.5.2.6", "2.5.2", "Desenvolvimento", "Chat dúvidas (IA)", 3, "Folha", 1, "", "Fase 3", "UC64", ""),
    ("2.5.2.7", "2.5.2", "Desenvolvimento", "Alerta compatibilidade navegador", 3, "Folha", 1, "", "Fase 2", "UC72", ""),
    ("2.5.3", "2.5", "Desenvolvimento", "Tipos de atividade — consumo (módulo educacional)", 2, "Grupo", 1, "", "", "", "12 tipos UC15; espelha 2.3.3"),
    ("2.5.3.1", "2.5.3", "Desenvolvimento", "Tipo — Evento Presencial", 3, "Folha", 1, "", "MVP", "UC40", ""),
    ("2.5.3.2", "2.5.3", "Desenvolvimento", "Tipo — Vídeo Aula", 3, "Folha", 1, "", "MVP", "UC37", ""),
    ("2.5.3.3", "2.5.3", "Desenvolvimento", "Tipo — Questionário Inicial", 3, "Folha", 1, "", "MVP", "UC39", ""),
    ("2.5.3.4", "2.5.3", "Desenvolvimento", "Tipo — Questionário Final", 3, "Folha", 1, "", "MVP", "UC39", ""),
    ("2.5.3.5", "2.5.3", "Desenvolvimento", "Tipo — Tarefa de Casa", 3, "Folha", 1, "", "MVP", "UC43", ""),
    ("2.5.3.6", "2.5.3", "Desenvolvimento", "Tipo — Download de Conteúdo", 3, "Folha", 1, "", "MVP", "UC36", ""),
    ("2.5.3.7", "2.5.3", "Desenvolvimento", "Tipo — Registro de Faturamento", 3, "Folha", 1, "", "MVP", "UC45", ""),
    ("2.5.3.8", "2.5.3", "Desenvolvimento", "Tipo — Atividade (questionário genérico)", 3, "Folha", 1, "", "Fase 2", "UC39", ""),
    ("2.5.3.9", "2.5.3", "Desenvolvimento", "Tipo — Aula ao Vivo", 3, "Folha", 1, "", "Fase 2", "UC38", ""),
    ("2.5.3.10", "2.5.3", "Desenvolvimento", "Tipo — Plano de Ação", 3, "Folha", 1, "", "Fase 2", "UC39", ""),
    ("2.5.3.11", "2.5.3", "Desenvolvimento", "Tipo — Visita Técnica", 3, "Folha", 1, "", "Fase 2", "UC78", ""),
    ("2.5.3.12", "2.5.3", "Desenvolvimento", "Tipo — NPS", 3, "Folha", 1, "", "Fase 2", "UC39", ""),
    ("2.6", "2", "Desenvolvimento", "Eventos de Comunicação", 1, "Grupo", 1, "10", "", "", "% inicial agregado"),
    ("2.6.1", "2.6", "Desenvolvimento", "Templates Meta (inscrição / aprovação)", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.6.2", "2.6", "Desenvolvimento", "Webhook / fila pós-cadastro WhatsApp", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.6.3", "2.6", "Desenvolvimento", "Disparo comunicar aprovação", 2, "Folha", 1, "", "MVP", "UC25", ""),
    ("2.6.4", "2.6", "Desenvolvimento", "Convite grupo turma P/H", 2, "Folha", 1, "", "MVP", "UC50", ""),
    ("2.6.5", "2.6", "Desenvolvimento", "Jornada online — liberar / OK / lote", 2, "Folha", 1, "", "MVP", "UC33", ""),
    ("2.6.6", "2.6", "Desenvolvimento", "Mensagens risco evasão online", 2, "Folha", 1, "", "Fase 2", "UC53", ""),
    ("2.6.7", "2.6", "Desenvolvimento", "Janela sáb 8h–16h + feriados", 2, "Folha", 1, "", "Fase 2", "", ""),
    ("2.7", "2", "Desenvolvimento", "BI e indicadores", 1, "Grupo", 1, "0", "", "", ""),
    ("2.7.1", "2.7", "Desenvolvimento", "Totais operacionais no Gestor", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.7.2", "2.7", "Desenvolvimento", "Dashboard Looker Studio", 2, "Folha", 1, "", "Fase 2", "UC59", ""),
    ("2.7.3", "2.7", "Desenvolvimento", "Relatórios quantitativos / qualitativos", 2, "Folha", 1, "", "Fase 2", "UC60, UC61", ""),
    ("2.7.4", "2.7", "Desenvolvimento", "Consumo WhatsApp", 2, "Folha", 1, "", "Fase 2", "UC65", ""),
    ("2.7.5", "2.7", "Desenvolvimento", "Base legada / totalizadores pregressos", 2, "Folha", 1, "", "Fase 3", "UC62, UC71", ""),
    ("2.8", "2", "Desenvolvimento", "Qualidade e piloto", 1, "Grupo", 1, "", "MVP", "", ""),
    ("2.8.1", "2.8", "Desenvolvimento", "Testes integrados ciclo completo", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.8.2", "2.8", "Desenvolvimento", "Homologação gestores (1 P/H + 1 online)", 2, "Folha", 1, "", "MVP", "", ""),
    ("2.8.3", "2.8", "Desenvolvimento", "Ajustes pós-piloto", 2, "Folha", 1, "", "Fase 2", "", ""),
]

FORMULA_ROLLUP = '=SE(F{row}="Grupo";SEERRO(MÉDIA(FILTRAR(H:H;B:B=$A{row};F:F="Folha"));"");H{row})'

OUTPUT = r"C:\Users\notte\OneDrive\Work\Consulado_da_Mulher\documentacao\Estrutura_Evolucao_Projeto.csv"

with open(OUTPUT, "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f, delimiter=";", quoting=csv.QUOTE_MINIMAL)
    writer.writerow([
        "ID", "ID_Pai", "Fase", "Atividade", "Nivel", "Tipo", "Peso",
        "Percentual", "Escopo", "UC", "Observacao", "Formula_Percentual",
    ])
    for i, row in enumerate(ROWS, start=2):
        formula = FORMULA_ROLLUP.format(row=i) if row[5] == "Grupo" else ""
        writer.writerow(list(row) + [formula])

print(f"Gerado: {OUTPUT} ({len(ROWS)} linhas, separador ; UTF-8 BOM)")
