import type { Outcome, Step } from "./types";

const ALL: Outcome[] = [
  "aprovada",
  "nao_qualificada",
  "nao_aprovada",
  "ausente",
];

function s(partial: Omit<Step, "journeys" | "outcomes"> & {
  journeys?: Step["journeys"];
  outcomes?: Step["outcomes"];
}): Step {
  return {
    journeys: ["online", "ph"],
    outcomes: ALL,
    ...partial,
  };
}

export const STEPS: Step[] = [
  s({
    id: "relogio_1_dia",
    phase: "inscricao",
    title: "Não finalizou em 1 dia",
    when: "1 dia depois da pré-inscrição, ficha ainda incompleta.",
    trigger: "relogio",
    channels: ["email", "whatsapp"],
    templateKey: "ficha_incompleta_d1",
    body: "Oi, {nome}. Vimos que você começou a inscrição no {programa}. Falta só terminar a ficha — toque para continuar de onde parou: {link}",
    naoFaz: "Não a coloca em seleção. Não começa o curso.",
  }),

  s({
    id: "relogio_3_dias",
    phase: "inscricao",
    title: "Não finalizou em 3 dias",
    when: "A ficha continua incompleta. Reforço a cada 3 dias.",
    trigger: "relogio",
    channels: ["email", "whatsapp"],
    templateKey: "ficha_incompleta_d3",
    body: "{nome}, ainda dá tempo de concluir sua ficha no {programa}. Um passo só: {link}",
    naoFaz: "Não acumula cobrança depois que ela termina. Não inicia o curso.",
  }),

  s({
    id: "ela_escreve_wa",
    phase: "inscricao",
    title: "Ela escreve no número do programa",
    when: "Online: depois da ficha, o app mostra o número. Ela manda a primeira mensagem.",
    trigger: "dela",
    channels: ["whatsapp"],
    templateKey: "",
    body: "Oi! Me inscrevi no {programa}.",
    naoFaz: "Não inicia o curso. Não é o OK da aula.",
    journeys: ["online"],
  }),

  s({
    id: "inscricao_recebida",
    phase: "inscricao",
    title: "Recebemos sua inscrição — aguarde a seleção",
    when: "Online: resposta imediata ao inbound. P/H: depois de finalizar a ficha.",
    trigger: "sistema",
    channels: ["whatsapp", "email"],
    templateKey: "inscricao_pos_inbound",
    body: "Oi, {nome}! Recebemos sua inscrição no {programa}. Agora é aguardar a seleção — a próxima fala será por aqui.",
    naoFaz: "Não começa o curso. Não pede OK. Não envia aula.",
  }),

  s({
    id: "classificar",
    phase: "selecao",
    title: "Gestora classifica (UC24)",
    when: "A unidade marca qualificada / em análise / não qualificada.",
    trigger: "gestora",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Classificar não envia WhatsApp, não aloca turma e não liga a jornada.",
    naoFaz: "Não comunica o resultado.",
  }),

  s({
    id: "convite_entrevista",
    phase: "selecao",
    title: "Convite à conversa de seleção",
    when: "UC25 faixa 1. Só P/H, só quem já está marcada numa sessão.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "selecao_convite_entrevista",
    body: "{nome}, você está convidada para a conversa de seleção do {programa} em {data}, às {hora}, em {local}. Confirme presença por aqui.",
    naoFaz: "Não aprova. Não cria o grupo. Não começa o curso.",
    journeys: ["ph"],
    outcomes: ["aprovada", "nao_aprovada", "ausente"],
  }),

  s({
    id: "presenca_entrevista",
    phase: "selecao",
    title: "Presença na entrevista",
    when: "No dia, a gestora marca presente. Só quem compareceu pode ser aprovada ou não.",
    trigger: "gestora",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Nada enviado. Aprovar no sistema ainda não manda mensagem.",
    naoFaz: "Não liga a jornada.",
    journeys: ["ph"],
    outcomes: ["aprovada", "nao_aprovada"],
  }),

  s({
    id: "ausente_entrevista",
    phase: "selecao",
    title: "Ausente à entrevista",
    when: "Falta sem realocação imediata. O sistema vira o status para não aprovada.",
    trigger: "sistema",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Ainda não há texto. O recado sai só quando a gestora comunica a faixa 3.",
    naoFaz: "Não dispara sozinho o template negativo.",
    journeys: ["ph"],
    outcomes: ["ausente"],
  }),

  s({
    id: "aprovar_sistema",
    phase: "selecao",
    title: "Aprovar no sistema",
    when: "P/H: gestora aprova quem compareceu. Aprovada ainda não entra na turma nem na jornada.",
    trigger: "gestora",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Nada enviado. Falta alocar turma e cadastrar o link do grupo.",
    naoFaz: "Não é o UC25 faixa 2.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "alocar_turma",
    phase: "selecao",
    title: "Alocar turma (UC17)",
    when: "Unidade aloca as aprovadas. Turma única = vínculo automático.",
    trigger: "gestora",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Alocar não muda o status de aprovação e não liga a jornada.",
    naoFaz: "Não envia WhatsApp.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "link_grupo",
    phase: "selecao",
    title: "Gestora cadastra o link do grupo",
    when: "O grupo é criado no WhatsApp (fora da API). O sistema só guarda o link.",
    trigger: "gestora",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Sem o link, a faixa 2 bloqueia.",
    naoFaz: "O sistema não cria o grupo.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "aprovada_online",
    phase: "selecao",
    title: "Você foi aprovada — boas-vindas (pede OK)",
    when: "UC25 faixa 2. Único início da jornada online. Já pede o primeiro OK. Não manda o lote.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "selecao_aprovacao",
    body: "{nome}, você está dentro do {programa}! Para receber as boas-vindas e o primeiro material, envie OK por aqui.",
    naoFaz: "Não envia vídeo nem exercício. Classificar sozinho não dispara isto.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "aprovada_ph",
    phase: "selecao",
    title: "Você foi aprovada — boas-vindas com link do grupo",
    when: "UC25 faixa 2. Único início da jornada P/H. Exige aprovada + turma + link.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "selecao_aprovacao_grupo",
    body: "{nome}, você está no {programa}! Entre no grupo da turma para efetivar a participação: {link_grupo}",
    naoFaz: "Não efetiva se ela não entrar no grupo. Não envia lote.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "nao_seguiu",
    phase: "selecao",
    title: "Desta vez não foi possível seguir",
    when: "UC25 faixa 3. Não qualificada, não aprovada ou ausente (sem realocar).",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "selecao_nao_aprovada",
    body: "{nome}, obrigada pelo interesse no {programa}. Nesta edição não foi possível seguir. Se abrir outra turma, falamos por aqui.",
    naoFaz: "Não liga o curso. Não cria grupo. Sem jargão de “reprovada”.",
    outcomes: ["nao_qualificada", "nao_aprovada", "ausente"],
    endsJourney: true,
  }),

  s({
    id: "nao_entrou_grupo",
    phase: "selecao",
    title: "Não entrou no grupo da turma",
    when: "P/H: quem não entra pelo link ainda não tem participação efetivada.",
    trigger: "dela",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "O curso no grupo não começa. A gestora confirma o ingresso na lista.",
    naoFaz: "Não dispara mais textos de encontro.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireNaoEntrouNoGrupo: true,
    endsJourney: true,
  }),

  s({
    id: "entrou_grupo",
    phase: "selecao",
    title: "Entrou no grupo — participação efetivada",
    when: "Ela abre o link do convite. Dali o dia a dia é o grupo.",
    trigger: "dela",
    channels: ["nota"],
    templateKey: "",
    body: "O papo um a um da gestora no grupo não é texto do catálogo. Os recados de encontro usam o mesmo texto do tipo de atividade.",
    naoFaz: "Não é WhatsApp pago da API.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),

  s({
    id: "ok_primeiro",
    phase: "curso",
    title: "Ela responde OK",
    when: "Primeiro OK depois da aprovação. Só então o lote sai.",
    trigger: "ok",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Pedir OK não marca a aula como feita. Feito é no aplicativo.",
    naoFaz: "Não entrega material sozinho — o lote é o passo seguinte.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "lote_boas_vindas",
    phase: "curso",
    title: "Primeiro lote — boas-vindas da jornada",
    when: "Parte do lote do primeiro OK.",
    trigger: "ok",
    channels: ["whatsapp", "email"],
    templateKey: "jornada_boas_vindas",
    body: "Bem-vinda, {nome}! Salve este número. Os materiais de apoio do {programa} estão no aplicativo: {link}",
    naoFaz: "Não substitui o aplicativo. Não marca módulo como concluído.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "lote_videoaula",
    phase: "curso",
    title: "Lote — videoaula",
    when: "Tipo de atividade no lote após OK.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "videoaula_v1",
    body: "{nome}, já está disponível sua aula sobre {titulo}. Assista no aplicativo até {prazo}: {link}",
    naoFaz: "Não marca a aula como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_exercicio",
    phase: "curso",
    title: "Lote — exercício",
    when: "Atividade prática no aplicativo.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "atividade_v1",
    body: "{nome}, seu desafio de {titulo} está no aplicativo: {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_tarefa",
    phase: "curso",
    title: "Lote — tarefa de casa",
    when: "Tarefa para o negócio, devolvida no aplicativo.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "tarefa_v1",
    body: "{nome}, a tarefa de casa ({titulo}) tem prazo até {prazo}: {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_saude",
    phase: "curso",
    title: "Lote — saúde financeira",
    when: "Hora de registrar números do negócio.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "faturamento_v1",
    body: "{nome}, vamos registrar os números do negócio (sem tom de auditoria): {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_download",
    phase: "curso",
    title: "Lote — material para baixar",
    when: "Texto e os arquivos no WhatsApp. Os mesmos ficam no aplicativo.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "download_v1",
    body: "{nome}, segue o material de {titulo} em anexo. Salve para consultar. Também está no app: {link}",
    naoFaz: "Não usa o checkbox de videoaula.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_plano",
    phase: "curso",
    title: "Lote — plano de ação",
    when: "Ela escreve o plano do negócio.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "plano_acao_v1",
    body: "{nome}, hora do plano de ação. O que precisa ter está no aplicativo: {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_q_inicial",
    phase: "curso",
    title: "Lote — questionário de chegada",
    when: "Começo do programa, para conhecer o ponto de partida.",
    trigger: "ok",
    channels: ["whatsapp"],
    templateKey: "quest_inicial_v1",
    body: "{nome}, queremos te conhecer. Responda o questionário de chegada (é sobre você, não sobre o negócio inteiro): {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "pedir_ok_aula",
    phase: "curso",
    title: "Já está disponível: envie OK",
    when: "O relógio da aula chegou. A aula está pronta, ainda não enviada.",
    trigger: "relogio",
    channels: ["whatsapp"],
    templateKey: "jornada_pedir_ok",
    body: "Já está disponível sua aula sobre {titulo}. Envie agora um OK para receber.",
    naoFaz: "Não entrega o material. Não marca a aula como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "grupo_presencial",
    phase: "curso",
    title: "Grupo — encontro presencial",
    when: "A gestora cola o texto do tipo no grupo, na data do encontro.",
    trigger: "gestora",
    channels: ["grupo"],
    templateKey: "aula_presencial_v1",
    body: "Turma, encontro presencial em {data}, {hora}, {local}. Levem caderno. Presença conta.",
    naoFaz: "Não marca presença. Não é API paga.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),
  s({
    id: "grupo_ao_vivo",
    phase: "curso",
    title: "Grupo — encontro ao vivo",
    when: "Encontro na mesma hora, pela tela. Não confundir com curso 100% online.",
    trigger: "gestora",
    channels: ["grupo"],
    templateKey: "aula_ao_vivo_v1",
    body: "Turma, encontro ao vivo em {data}, {hora}. Link da sala no aplicativo: {link}",
    naoFaz: "Não marca presença.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),
  s({
    id: "grupo_videoaula",
    phase: "curso",
    title: "Grupo — videoaula",
    when: "Mesmo texto do catálogo, colado no grupo.",
    trigger: "gestora",
    channels: ["grupo"],
    templateKey: "videoaula_v1",
    body: "Turma, videoaula {titulo} disponível até {prazo}: {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),
  s({
    id: "grupo_tarefa",
    phase: "curso",
    title: "Grupo — tarefa de casa",
    when: "Mesmo texto do tipo Tarefa.",
    trigger: "gestora",
    channels: ["grupo"],
    templateKey: "tarefa_v1",
    body: "Turma, tarefa de casa ({titulo}) até {prazo}: {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),
  s({
    id: "grupo_saude",
    phase: "curso",
    title: "Grupo — saúde financeira",
    when: "Mesmo texto do tipo.",
    trigger: "gestora",
    channels: ["grupo"],
    templateKey: "faturamento_v1",
    body: "Turma, hora de registrar os números do negócio: {link}",
    naoFaz: "Não marca como feita.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),
  s({
    id: "mentoria_ph",
    phase: "curso",
    title: "Mentoria disponível (durante o programa)",
    when: "P/H: ela pede ou a gestora inclui. Combinado fino com a mentora é 1:1, fora do catálogo.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "mentoria_disponivel",
    body: "{nome}, a mentoria do {programa} está disponível. Próximo passo no aplicativo: {link}",
    naoFaz: "Não marca a sessão como feita. Não substitui o treino da voluntária.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),
  s({
    id: "silencio_15",
    phase: "curso",
    title: "Programa longo: 15 dias de silêncio",
    when: "P/H, vários meses: 15 dias sem participação relevante e muita coisa atrasada.",
    trigger: "gestora",
    channels: ["grupo"],
    templateKey: "risco_longo_ph",
    body: "Turma do {programa}: sentimos sua falta. Se algo travou, fala com a gente no grupo. Vamos juntas.",
    naoFaz: "Não envia lote. Não usa a regra de 10 dias do online. Não é o número do programa sozinho.",
    journeys: ["ph"],
    outcomes: ["aprovada"],
    requireEntrouNoGrupo: true,
  }),

  s({
    id: "relogio_prazo",
    phase: "curso",
    title: "Relógio: horas antes do prazo",
    when: "Atividade com data limite, ainda não feita.",
    trigger: "relogio",
    channels: ["whatsapp", "email"],
    templateKey: "activity_deadline_soon",
    body: "{nome}, o prazo de {titulo} é {prazo}. Toque para fazer: {link}",
    naoFaz: "Não prorroga o prazo. Não envia o lote.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "relogio_fila",
    phase: "curso",
    title: "Relógio: várias aulas liberadas e não feitas",
    when: "A fila passa o limiar da edição. Maratonar é esperado.",
    trigger: "relogio",
    channels: ["whatsapp", "email"],
    templateKey: "backlog_liberadas",
    body: "{nome}, você tem conteúdos prontos no {programa}. Juntar e fazer depois é ok — o programa tem fim. App: {link}",
    naoFaz: "Não classifica como evasão.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "relogio_5_dias",
    phase: "curso",
    title: "Relógio: 5 dias do fim, ainda com pendência",
    when: "Curso pela internet; faltam 5 dias e ainda há atividade não feita.",
    trigger: "relogio",
    channels: ["whatsapp", "email"],
    templateKey: "edition_ending_pending",
    body: "{nome}, o {programa} acaba em 5 dias e ainda há pendência. App: {link}",
    naoFaz: "Não abre prazo extra.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "relogio_10_dias",
    phase: "curso",
    title: "Relógio: 10 dias sem fazer aula já liberada",
    when: "Estado de risco do curso curto. Quem só está juntando e ainda entra no app não entra.",
    trigger: "relogio",
    channels: ["whatsapp", "email"],
    templateKey: "risk_short_online",
    body: "{nome}, faz 10 dias que a aula de {titulo} está pronta. Um passo leve: {link}",
    naoFaz: "Não é o mesmo que 15 dias de silêncio do P/H.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "relogio_d15",
    phase: "curso",
    title: "Relógio: por volta do 15º dia",
    when: "Janela automática de 3 a 5 dias no meio da formação curta, se a unidade ligou.",
    trigger: "relogio",
    channels: ["whatsapp", "email"],
    templateKey: "checkpoint_d15",
    body: "{nome}, estamos no meio do {programa}. Ainda dá tempo. App: {link}",
    naoFaz: "Não mistura com o filtro de 10 dias / 5 dias do fim.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "resgate_manual",
    phase: "curso",
    title: "Gestora confirma resgate (risco de evasão)",
    when: "A lista mostra o risco; sem o clique dela a mensagem não sai.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "resgate_risco",
    body: "{nome}, sentimos sua falta no {programa}. Quando puder, retoma por aqui: {link}",
    naoFaz: "Não envia o lote. Não pede OK no lugar da aula.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "nao_fez_atividade",
    phase: "curso",
    title: "Gestora: quem não fez uma atividade",
    when: "Ela escolhe uma atividade e dispara para quem ainda não concluiu.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "pendencia_atividade",
    body: "{nome}, a atividade {titulo} ainda está com você (prazo {prazo}): {link}",
    naoFaz: "Não marca risco. Não envia o lote.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "campanha_meio",
    phase: "curso",
    title: "Gestora: campanha de meio de curso",
    when: "Por volta do 15º dia, 3 a 5 dias, recorte que ela escolher.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "campanha_meio_curso",
    body: "{nome}, um empurrão no meio do {programa}. O que ainda dá tempo está no app: {link}",
    naoFaz: "Não substitui o OK do conteúdo.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "convite_live",
    phase: "encerramento",
    title: "Convite da live e últimos passos",
    when: "Online: o negócio fez todas as atividades. A gestora dispara o convite.",
    trigger: "gestora",
    channels: ["email", "whatsapp"],
    templateKey: "convite_live",
    body: "{nome}, você chegou a 100% no {programa}. Live em {data}, {hora}: {link_live}. Depois, palavra-chave e questionário no app: {link}",
    naoFaz: "Assistir à live, sozinha, não libera doação.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "lote_q_final",
    phase: "encerramento",
    title: "Questionário final",
    when: "Depois da live e da palavra-chave, quando a edição usar esse funil.",
    trigger: "sistema",
    channels: ["whatsapp"],
    templateKey: "quest_final_v1",
    body: "{nome}, feche o aprendizado no questionário final: {link}",
    naoFaz: "Acertar o quiz não aprova doação.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),
  s({
    id: "mentoria_online",
    phase: "encerramento",
    title: "Mentoria disponível (encerramento)",
    when: "Online: equipe abre mentoria para quem chegou ao fim / teve doação aprovada.",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "mentoria_disponivel",
    body: "{nome}, a mentoria do {programa} está aberta. Preencha o diagnóstico: {link}",
    naoFaz: "Não marca a sessão como feita.",
    journeys: ["online"],
    outcomes: ["aprovada"],
  }),

  s({
    id: "doacao_aprovada",
    phase: "encerramento",
    title: "Doação aprovada — dados de recebimento",
    when: "Unidade aprovou (online: depois do funil live + quiz).",
    trigger: "gestora",
    channels: ["whatsapp", "email"],
    templateKey: "doacao_aprovada",
    body: "{nome}, sua doação foi aprovada. Informe PIX ou endereço no aplicativo e aguarde a educadora — sem data prometida: {link}",
    naoFaz: "Não promete dia de crédito. Não é o comprovante.",
    outcomes: ["aprovada"],
    requireDoacao: true,
  }),
  s({
    id: "recibo_doacao",
    phase: "encerramento",
    title: "Recibo da doação",
    when: "Antes do pagamento (dinheiro) ou depois que ela confirma recebimento (produto).",
    trigger: "sistema",
    channels: ["whatsapp", "email"],
    templateKey: "doacao_recibo",
    body: "{nome}, seu recibo está no aplicativo para assinar: {link}",
    naoFaz: "Não substitui a conferência da equipe.",
    outcomes: ["aprovada"],
    requireDoacao: true,
  }),
  s({
    id: "sem_doacao",
    phase: "encerramento",
    title: "Sem doação nesta edição / neste recorte",
    when: "A equipe não aprovou doação para este negócio.",
    trigger: "sistema",
    channels: ["nenhum"],
    templateKey: "",
    silent: true,
    body: "Nenhum texto de doação. O certificado do programa é outro recado.",
    naoFaz: "Não envia dados de PIX.",
    outcomes: ["aprovada"],
    requireSemDoacao: true,
  }),

  s({
    id: "certificado",
    phase: "encerramento",
    title: "Certificado do programa",
    when: "O negócio atinge o percentual da edição. Todas as sócias recebem.",
    trigger: "sistema",
    channels: ["whatsapp", "email"],
    templateKey: "certificado_programa",
    body: "Parabéns, {nome}! Seu certificado do {programa} está em PDF neste WhatsApp e no aplicativo: {link}",
    naoFaz: "Não é o certificado da mentoria nem o da voluntária.",
    outcomes: ["aprovada"],
  }),
  s({
    id: "programa_acabou",
    phase: "encerramento",
    title: "O programa acabou",
    when: "A edição encerra o ciclo de formação.",
    trigger: "sistema",
    channels: ["whatsapp", "email"],
    templateKey: "programa_encerrado",
    body: "{nome}, o ciclo do {programa} encerrou. O aplicativo continua com você. Em cerca de 30 dias, uma pesquisa curta.",
    naoFaz: "Não apaga o acesso. Não dispara a pesquisa de 30 dias.",
    outcomes: ["aprovada"],
  }),
  s({
    id: "pesquisa_d30",
    phase: "encerramento",
    title: "Pesquisa cerca de 30 dias depois",
    when: "Relógio ~30 dias após o encerramento.",
    trigger: "relogio",
    channels: ["whatsapp", "email"],
    templateKey: "pesquisa_pos_d30",
    body: "{nome}, e o seu negócio agora? Poucos minutos no aplicativo: {link}",
    naoFaz: "Não reabre o curso. Não é o questionário final da live.",
    outcomes: ["aprovada"],
    endsJourney: true,
  }),
];
